import type { Product } from "./types";


export const products: Product[] = [
  // ─── WATCHES ────────────────────────────────────────────────────────────────
  {
    id: "chrono-black",
    slug: "chrono-black",
    sku: "LR-CHRONO-BLK",
    name: "Chrono Black",
    category: "watches",
    price: 175,
    originalPrice: 279,
    currency: "€",
    inStock: true,
    warranty: "2 години гаранция",
    shortDescription: "Италиански дизайн. Японска точност.",
    description:
      "Chrono Black въплъщава мощта на нощта в изчистен хронограф. Корпусът от премиум неръждаема стомана 316L, частично скелетизираният многослоен циферблат и сапфиреното кристално стъкло създават часовник, който изразява характер без усилие. Механизмът издържа минимум 10 години. Хипоалергенната силиконова каишка осигурява комфорт при продължително носене.",
    features: [
      "Сапфирен кристал - изключителна яснота и защита от надраскване",
      "Японски кварцов механизъм - прецизност за поне 10 години",
      "Водоустойчивост 5 ATM / 50 м",
      "316L неръждаема стомана - хипоалергенна, нержавяваща",
      "Хронограф с многофункционален циферблат",
      "Хипоалергенна дишаща силиконова каишка",
    ],
    specs: [
      { label: "Корпус", value: "Премиум неръждаема стомана 316L" },
      { label: "Размери", value: "43 мм × 50 мм × 16 мм" },
      { label: "Стъкло", value: "Сапфирен кристал" },
      { label: "Механизъм", value: "Японски кварцов хронограф" },
      { label: "Циферблат", value: "Частично скелетизиран, многослоен" },
      { label: "Каишка", value: "Хипоалергенен силикон" },
      { label: "Водоустойчивост", value: "5 ATM / 50 м" },
    ],
    coverImage: {
      src: `/Products/watches/Chrono Black/chrono-black-hronograf-preden-izgled.webp`,
      alt: "Lorenzo Ricci Chrono Black луксозен хронограф - преден изглед, 316L стомана сапфирен кристал",
    },
    images: [
      { src: `/Products/watches/Chrono Black/chrono-black-hronograf-preden-izgled.webp`,  alt: "Lorenzo Ricci Chrono Black хронограф - преден изглед, японски кварцов механизъм" },
      { src: `/Products/watches/Chrono Black/chrono-black-lume-noshten-rejim.webp`,        alt: "Lorenzo Ricci Chrono Black нощен режим - светещи маркери lume, циферблат детайл" },
      { src: `/Products/watches/Chrono Black/chrono-black-lifestyle.webp`,                 alt: "Lorenzo Ricci Chrono Black - лайфстайл снимка, луксозен мъжки часовник" },
      { src: `/Products/watches/Chrono Black/chrono-black-zadna-strana.webp`,              alt: "Lorenzo Ricci Chrono Black - задна страна на корпуса 316L неръждаема стомана" },
      { src: `/Products/watches/Chrono Black/chrono-black-stranicen-izgled.webp`,          alt: "Lorenzo Ricci Chrono Black - страничен изглед, водоустойчивост 5 ATM" },
      { src: `/Products/watches/Chrono Black/chrono-black-kutiya-otvorena.webp`,           alt: "Lorenzo Ricci Chrono Black в луксозна кутия - подаръчна опаковка отворена" },
      { src: `/Products/watches/Chrono Black/chrono-black-kutiya-zatvorena.webp`,          alt: "Lorenzo Ricci Chrono Black затворена подаръчна кутия" },
      { src: `/Products/watches/Chrono Black/chrono-black-skeletiziran-tsiferbat.webp`,    alt: "Lorenzo Ricci Chrono Black - детайл на хронографа, скелетизиран циферблат" },
    ],
    descriptionImages: [
      { src: `/Products/watches/Chrono Black/description/chrono-black-editorial.webp`, alt: "Lorenzo Ricci Chrono Black - лайфстайл editorial, луксозен хронограф" },
      { src: `/Products/watches/Chrono Black/chrono-black-lifestyle.webp`,             alt: "Lorenzo Ricci Chrono Black - lifestyle снимка на китката" },
    ],
    quoteVideo: "/chrono-black-quote.mp4",
  },
  {
    id: "golden-eclipse",
    slug: "golden-eclipse",
    sku: "LR-MIDNIGHT-ECL",
    name: "Golden Eclipse",
    category: "watches",
    price: 195,
    originalPrice: 279,
    currency: "€",
    badge: "Последни бройки",
    inStock: true,
    warranty: "2 години гаранция",
    shortDescription: "Италиански дизайн. Японска точност.",
    description:
      "Golden Eclipse е ода към слънцето - великолепен хронограф, създаден за тези, които носят успеха си на китката. Позлатеният корпус от стомана 316L, скелетизираният циферблат и сапфиреното стъкло съставят силует с незаменимо присъствие. Изтънчен италиански дизайн и майсторска изработка, в която всеки детайл има значение.",
    features: [
      "Сапфирен кристал - изключителна яснота и защита от надраскване",
      "Японски кварцов механизъм - прецизност за поне 10 години",
      "Водоустойчивост 5 ATM / 50 м",
      "316L неръждаема стомана - хипоалергенна, нержавяваща",
      "Хронограф с многофункционален циферблат",
      "Хипоалергенна дишаща силиконова каишка",
    ],
    specs: [
      { label: "Корпус", value: "Премиум неръждаема стомана 316L" },
      { label: "Размери", value: "43 мм × 50 мм × 16 мм" },
      { label: "Стъкло", value: "Сапфирен кристал" },
      { label: "Механизъм", value: "Японски кварцов хронограф" },
      { label: "Циферблат", value: "Частично скелетизиран, многослоен" },
      { label: "Каишка", value: "Хипоалергенен силикон" },
      { label: "Водоустойчивост", value: "5 ATM / 50 м" },
    ],
    coverImage: {
      src: `/Products/watches/Golden Eclipse/golden-eclipse-hronograf-preden-izgled.webp`,
      alt: "Lorenzo Ricci Golden Eclipse луксозен хронограф - позлатен корпус 316L стомана сапфирен кристал",
    },
    images: [
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-hronograf-preden-izgled.webp`, alt: "Lorenzo Ricci Golden Eclipse хронограф - преден изглед, позлатен корпус 18K PVD" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-lume-noshten-rejim.webp`,      alt: "Lorenzo Ricci Golden Eclipse нощен режим - светещи маркери lume, скелетизиран циферблат" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-lifestyle-1.webp`,             alt: "Lorenzo Ricci Golden Eclipse - лайфстайл снимка, луксозен мъжки часовник" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-lifestyle-2.webp`,             alt: "Lorenzo Ricci Golden Eclipse - лайфстайл снимка, италиански дизайн" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-pozlaten-tsiferbat.webp`,      alt: "Lorenzo Ricci Golden Eclipse - детайл на позлатения циферблат 18K PVD" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-zadna-strana.webp`,            alt: "Lorenzo Ricci Golden Eclipse - задна страна на корпуса, 316L неръждаема стомана" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-stranicen-izgled.webp`,        alt: "Lorenzo Ricci Golden Eclipse - страничен изглед, водоустойчивост 5 ATM" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-kaishka-kopchalka.webp`,       alt: "Lorenzo Ricci Golden Eclipse - закопчалка, хипоалергенна силиконова каишка" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-kutiya-otvorena.webp`,         alt: "Lorenzo Ricci Golden Eclipse в луксозна кутия - подаръчна опаковка отворена" },
      { src: `/Products/watches/Golden Eclipse/golden-eclipse-kutiya-zatvorena.webp`,        alt: "Lorenzo Ricci Golden Eclipse затворена подаръчна кутия" },
    ],
    descriptionImages: [
      { src: `/Products/watches/Golden Eclipse/description/golden-eclipse-editorial-1.webp`, alt: "Lorenzo Ricci Golden Eclipse - editorial лайфстайл, позлатен хронограф" },
      { src: `/Products/watches/Golden Eclipse/description/golden-eclipse-editorial-2.webp`, alt: "Lorenzo Ricci Golden Eclipse - луксозен детайл на позлатения циферблат" },
    ],
    quoteVideo: "/golden-eclipse-quote.mp4",
  },
  {
    id: "polar-frost",
    slug: "polar-frost",
    sku: "LR-POLAR-FROST",
    name: "Polar Frost",
    category: "watches",
    price: 175,
    originalPrice: 279,
    currency: "€",
    inStock: true,
    warranty: "2 години гаранция",
    shortDescription: "Италиански дизайн. Японска точност.",
    description:
      "Polar Frost носи хладната увереност на арктическата синева. Прецизно изработеният корпус от стомана 316L, сапфиреното кристално стъкло и хронографът с многослоен циферблат правят от Polar Frost часовник за хора с ясен вкус. Водоустойчивост 5 ATM - спокойствие за всяко приключение.",
    features: [
      "Сапфирен кристал - изключителна яснота и защита от надраскване",
      "Японски кварцов механизъм - прецизност за поне 10 години",
      "Водоустойчивост 5 ATM / 50 м",
      "316L неръждаема стомана - хипоалергенна, нержавяваща",
      "Хронограф с многофункционален циферблат",
      "Хипоалергенна дишаща силиконова каишка",
    ],
    specs: [
      { label: "Корпус", value: "Премиум неръждаема стомана 316L" },
      { label: "Размери", value: "43 мм × 50 мм × 16 мм" },
      { label: "Стъкло", value: "Сапфирен кристал" },
      { label: "Механизъм", value: "Японски кварцов хронограф" },
      { label: "Циферблат", value: "Частично скелетизиран, многослоен" },
      { label: "Каишка", value: "Хипоалергенен силикон" },
      { label: "Водоустойчивост", value: "5 ATM / 50 м" },
    ],
    coverImage: {
      src: `/Products/watches/Polar Frost/polar-frost-hronograf-preden-izgled.webp`,
      alt: "Lorenzo Ricci Polar Frost луксозен хронограф - синя арктическа версия, сапфирен кристал",
    },
    images: [
      { src: `/Products/watches/Polar Frost/polar-frost-hronograf-preden-izgled.webp`, alt: "Lorenzo Ricci Polar Frost хронограф - преден изглед, арктическо синьо" },
      { src: `/Products/watches/Polar Frost/polar-frost-lume-noshten-rejim.webp`,      alt: "Lorenzo Ricci Polar Frost нощен режим lume - светещи маркери, арктически дизайн" },
      { src: `/Products/watches/Polar Frost/polar-frost-lifestyle-1.webp`,             alt: "Lorenzo Ricci Polar Frost - лайфстайл снимка, луксозен мъжки часовник" },
      { src: `/Products/watches/Polar Frost/polar-frost-lifestyle-2.webp`,             alt: "Lorenzo Ricci Polar Frost - лайфстайл снимка, италиански дизайн" },
      { src: `/Products/watches/Polar Frost/polar-frost-zadna-strana.webp`,            alt: "Lorenzo Ricci Polar Frost - задна страна на корпуса, 316L неръждаема стомана" },
      { src: `/Products/watches/Polar Frost/polar-frost-stranicen-izgled.webp`,        alt: "Lorenzo Ricci Polar Frost - страничен изглед, водоустойчивост 5 ATM" },
      { src: `/Products/watches/Polar Frost/polar-frost-kaishka-kopchalka.webp`,       alt: "Lorenzo Ricci Polar Frost - закопчалка, хипоалергенна силиконова каишка" },
      { src: `/Products/watches/Polar Frost/polar-frost-kutiya-otvorena.webp`,         alt: "Lorenzo Ricci Polar Frost в луксозна кутия - подаръчна опаковка отворена" },
      { src: `/Products/watches/Polar Frost/polar-frost-kutiya-zatvorena.webp`,        alt: "Lorenzo Ricci Polar Frost затворена подаръчна кутия" },
    ],
    descriptionImages: [
      { src: `/Products/watches/Polar Frost/description/polar-frost-editorial-1.webp`, alt: "Lorenzo Ricci Polar Frost - editorial лайфстайл, арктически хронограф" },
      { src: `/Products/watches/Polar Frost/description/polar-frost-editorial-2.webp`, alt: "Lorenzo Ricci Polar Frost - детайл на синия циферблат, арктическа колекция" },
    ],
    descriptionVideo: "/polar-frost-description.mp4",
  },

  // ─── JEWELLERY ───────────────────────────────────────────────────────────────
  {
    id: "bracelet-diamante-cross",
    slug: "bracelet-diamante-cross",
    sku: "GR-DIAMANTE-CROSS",
    name: "Гривна Diamante Cross",
    category: "jewellery",
    subcategory: "bracelet",
    price: 39,
    currency: "€",
    badge: "Ограничена наличност",
    inStock: true,
    warranty: "Доживотна гаранция",
    shortDescription: "Италианска естетика в съвременна форма",
    description:
      "Гривна Diamante Cross съчетава изчистеността на модерния дизайн с дълбочината на символиката. Кръстът, украсен с циркониеви камъни, грее на слънце с благороден блясък. Изработена от премиум стомана 316L с 4-слойно 18K PVD златно покритие - устойчива на вода, пот и парфюм. Унисекс. Носи се сама или в комбинация с часовник.",
    features: [
      "4-слойно 18K PVD златно покритие - не избледнява",
      "Циркониеви камъни с благороден блясък",
      "Устойчива на вода, пот и парфюм",
      "Унисекс дизайн - 18+4 см регулируема дължина",
      "Хипоалергенна 316L неръждаема стомана",
      "Физически печат 'ITALY' - вграден символ на италианския дизайн",
    ],
    specs: [
      { label: "Материал", value: "316L неръждаема стомана с 18K PVD покритие" },
      { label: "Дължина", value: "18 + 4 см (регулируема)" },
      { label: "Покритие", value: "4-слойно 18K PVD златно" },
      { label: "Печат", value: "750 IT" },
      { label: "Пол", value: "Унисекс" },
    ],
    coverImage: {
      src: `/Products/jewellery/bracelet Diamante Cross/grivna-diamante-cross-18k-pvd-preden-izgled.webp`,
      alt: "Гривна Diamante Cross Lorenzo Ricci - 18K PVD позлата, циркониев кръст, 316L стомана",
    },
    images: [
      { src: `/Products/jewellery/bracelet Diamante Cross/grivna-diamante-cross-18k-pvd-preden-izgled.webp`, alt: "Гривна Diamante Cross Lorenzo Ricci - продуктова снимка бял фон, 18K PVD злато" },
      { src: `/Products/jewellery/bracelet Diamante Cross/grivna-diamante-cross-detal-tsirkoniev-krast.webp`, alt: "Гривна Diamante Cross - детайл на циркониевия кръст, луксозна гривна" },
      { src: `/Products/jewellery/bracelet Diamante Cross/grivna-diamante-cross-lifestyle.webp`,               alt: "Гривна Diamante Cross - лайфстайл снимка, носена на китката" },
      { src: `/Products/jewellery/bracelet Diamante Cross/grivna-diamante-cross-stranicen-izgled.webp`,        alt: "Гривна Diamante Cross - страничен изглед, дебелина и детайл на закопчалката" },
      { src: `/Products/jewellery/bracelet Diamante Cross/grivna-diamante-cross-kutiya.webp`,                  alt: "Гривна Diamante Cross в подаръчна кутия Lorenzo Ricci" },
    ],
  },
  {
    id: "bracelet-milano-forte",
    slug: "bracelet-milano-forte",
    sku: "GR-FORTE",
    name: "Гривна Milano Forte",
    category: "jewellery",
    subcategory: "bracelet",
    price: 32,
    originalPrice: 49,
    currency: "€",
    inStock: true,
    warranty: "Доживотна гаранция",
    shortDescription: "Италианска естетика в съвременна форма",
    description:
      "Milano Forte е масивна плетена гривна с плътно 18K PVD златно покритие - тежи приятно и изглежда внушително. Ширина 8 мм. Дължина 20 см (може да бъде скъсена при бижутер). Комбинира се перфектно с часовник или като самостоятелен акцент. Устойчива на вода, пот и парфюм.",
    features: [
      "4-слойно 18K PVD златно покритие - не избледнява",
      "Ширина 8 мм - масивен, внушителен вид",
      "Устойчива на вода, пот и парфюм",
      "Хипоалергенна 316L неръждаема стомана",
      "Физически печат 'ITALY' - вграден символ на италианския дизайн",
    ],
    specs: [
      { label: "Материал", value: "316L неръждаема стомана с 18K PVD покритие" },
      { label: "Ширина", value: "8 мм" },
      { label: "Дължина", value: "20 см" },
      { label: "Покритие", value: "4-слойно 18K PVD златно" },
      { label: "Печат", value: "750 IT" },
    ],
    coverImage: {
      src: `/Products/jewellery/Bracelet Milano Forte/grivna-milano-forte-18k-pvd-preden-izgled.webp`,
      alt: "Гривна Milano Forte Lorenzo Ricci - масивна 8мм 18K PVD позлата, 316L стомана",
    },
    images: [
      { src: `/Products/jewellery/Bracelet Milano Forte/grivna-milano-forte-18k-pvd-preden-izgled.webp`, alt: "Гривна Milano Forte Lorenzo Ricci - продуктова снимка бял фон, 18K PVD злато" },
      { src: `/Products/jewellery/Bracelet Milano Forte/grivna-milano-forte-lifestyle.webp`,              alt: "Гривна Milano Forte - лайфстайл снимка, носена на китката" },
      { src: `/Products/jewellery/Bracelet Milano Forte/grivna-milano-forte-detal-pletka-8mm.webp`,       alt: "Гривна Milano Forte - детайл на плетката, ширина 8мм" },
      { src: `/Products/jewellery/Bracelet Milano Forte/grivna-milano-forte-kopchalka.webp`,              alt: "Гривна Milano Forte - детайл на закопчалката, 750 IT печат" },
      { src: `/Products/jewellery/Bracelet Milano Forte/grivna-milano-forte-kutiya.webp`,                 alt: "Гривна Milano Forte в подаръчна кутия Lorenzo Ricci" },
    ],
  },
  {
    id: "bracelet-milano-twist",
    slug: "bracelet-milano-twist",
    sku: "GR-MILANO-TWIST",
    name: "Гривна Milano Twist",
    category: "jewellery",
    subcategory: "bracelet",
    price: 32,
    originalPrice: 44,
    currency: "€",
    inStock: true,
    warranty: "Доживотна гаранция",
    shortDescription: "Италианска естетика в съвременна форма",
    description:
      "Milano Twist е изтънчена усукана гривна с 18K PVD позлата. Елегантна усукана плетка, красива сама или наредена с друга гривна от колекцията. Устойчива на вода, пот и парфюм. Хипоалергенна 316L стомана.",
    features: [
      "4-слойно 18K PVD златно покритие - не избледнява",
      "Усукана плетка - уникален характер",
      "Устойчива на вода, пот и парфюм",
      "Хипоалергенна 316L неръждаема стомана",
      "Физически печат 'ITALY' - вграден символ на италианския дизайн",
    ],
    specs: [
      { label: "Материал", value: "316L неръждаема стомана с 18K PVD покритие" },
      { label: "Покритие", value: "4-слойно 18K PVD златно" },
      { label: "Печат", value: "750 IT" },
    ],
    coverImage: {
      src: `/Products/jewellery/Bracelet Milano Twist/grivna-milano-twist-18k-pvd-preden-izgled.webp`,
      alt: "Гривна Milano Twist Lorenzo Ricci - усукана плетка 18K PVD позлата, 316L стомана",
    },
    images: [
      { src: `/Products/jewellery/Bracelet Milano Twist/grivna-milano-twist-18k-pvd-preden-izgled.webp`, alt: "Гривна Milano Twist Lorenzo Ricci - продуктова снимка бял фон, 18K PVD злато" },
      { src: `/Products/jewellery/Bracelet Milano Twist/grivna-milano-twist-lifestyle.webp`,               alt: "Гривна Milano Twist - лайфстайл снимка, носена на китката" },
      { src: `/Products/jewellery/Bracelet Milano Twist/grivna-milano-twist-detal-usukana-pletka.webp`,    alt: "Гривна Milano Twist - детайл на усуканата плетка, италиански дизайн" },
      { src: `/Products/jewellery/Bracelet Milano Twist/grivna-milano-twist-kopchalka.webp`,               alt: "Гривна Milano Twist - детайл на закопчалката, 750 IT печат" },
      { src: `/Products/jewellery/Bracelet Milano Twist/grivna-milano-twist-kutiya.webp`,                  alt: "Гривна Milano Twist в подаръчна кутия Lorenzo Ricci" },
    ],
  },
  {
    id: "bracelet-signature",
    slug: "bracelet-signature",
    sku: "GR-SIGNATURE",
    name: "Гривна Signature",
    category: "jewellery",
    subcategory: "bracelet",
    price: 37,
    originalPrice: 55,
    currency: "€",
    inStock: true,
    warranty: "Доживотна гаранция",
    shortDescription: "Италианска естетика в съвременна форма",
    description:
      "Гривна Signature е квинтесенцията на марката Lorenzo Ricci - изчистена, уверена и вечна. Ширина 6 мм, дължина 22 см. 4-слойно 18K PVD покритие. Хипоалергенна. Носи се с всяко облекло и при всеки повод.",
    features: [
      "4-слойно 18K PVD златно покритие - не избледнява",
      "Ширина 6 мм - изчистен, класически вид",
      "Дължина 22 см - универсална",
      "Устойчива на вода, пот и парфюм",
      "Хипоалергенна 316L неръждаема стомана",
    ],
    specs: [
      { label: "Материал", value: "316L неръждаема стомана с 18K PVD покритие" },
      { label: "Ширина", value: "6 мм" },
      { label: "Дължина", value: "22 см" },
      { label: "Покритие", value: "4-слойно 18K PVD златно" },
      { label: "Печат", value: "750 IT" },
    ],
    coverImage: {
      src: `/Products/jewellery/Bracelet Signature/grivna-signature-18k-pvd-preden-izgled.webp`,
      alt: "Гривна Signature Lorenzo Ricci - класическа 6мм 18K PVD позлата, 316L стомана",
    },
    images: [
      { src: `/Products/jewellery/Bracelet Signature/grivna-signature-18k-pvd-preden-izgled.webp`, alt: "Гривна Signature Lorenzo Ricci - продуктова снимка бял фон, 18K PVD злато" },
      { src: `/Products/jewellery/Bracelet Signature/grivna-signature-lifestyle.webp`,              alt: "Гривна Signature - лайфстайл снимка, носена на китката" },
      { src: `/Products/jewellery/Bracelet Signature/grivna-signature-detal-pletka-6mm.webp`,       alt: "Гривна Signature - детайл на плетката, ширина 6мм" },
      { src: `/Products/jewellery/Bracelet Signature/grivna-signature-kopchalka.webp`,              alt: "Гривна Signature - детайл на закопчалката, 750 IT печат" },
      { src: `/Products/jewellery/Bracelet Signature/grivna-signature-kutiya.webp`,                 alt: "Гривна Signature в подаръчна кутия Lorenzo Ricci" },
    ],
  },
  {
    id: "necklace-aurelius",
    slug: "necklace-aurelius",
    sku: "KO-AURELIUS-CROSS",
    name: "Колие Aurelius Cross",
    category: "jewellery",
    subcategory: "necklace",
    price: 42,
    currency: "€",
    badge: "Ограничена наличност",
    inStock: true,
    warranty: "Доживотна гаранция",
    shortDescription: "Италианска естетика в съвременна форма",
    description:
      "Колие Aurelius Cross носи духа на вечния Рим - кръстът, дълбоко и равномерно покрит с 18K PVD злато. Размери на кръста 3.7 × 2 см, дебелина 3 мм. Верижка с дължина 60 см. Устойчиво на вода, пот и парфюм. Хипоалергенно. Доживотна гаранция.",
    features: [
      "4-слойно 18K PVD златно покритие - не избледнява",
      "Кръст 3.7 × 2 см - значимо присъствие",
      "Дължина на верижката 60 см",
      "Устойчиво на вода, пот и парфюм",
      "Хипоалергенна 316L неръждаема стомана",
      "Физически печат 'ITALY' - вграден символ на италианския дизайн",
    ],
    specs: [
      { label: "Материал", value: "316L неръждаема стомана с 18K PVD покритие" },
      { label: "Размер на кръста", value: "3.7 × 2 см" },
      { label: "Дебелина", value: "3 мм" },
      { label: "Дължина", value: "60 см" },
      { label: "Покритие", value: "4-слойно 18K PVD златно" },
      { label: "Печат", value: "750 IT" },
    ],
    coverImage: {
      src: `/Products/jewellery/Necklace Aurelius Cross/kolie-aurelius-cross-18k-pvd-preden-izgled.webp`,
      alt: "Колие Aurelius Cross Lorenzo Ricci - 18K PVD позлата, кръст 3.7×2см, 316L стомана",
    },
    images: [
      { src: `/Products/jewellery/Necklace Aurelius Cross/kolie-aurelius-cross-18k-pvd-preden-izgled.webp`, alt: "Колие Aurelius Cross Lorenzo Ricci - продуктова снимка бял фон, 18K PVD злато" },
      { src: `/Products/jewellery/Necklace Aurelius Cross/kolie-aurelius-cross-detal-krast.webp`,            alt: "Колие Aurelius Cross - детайл на кръста, размери 3.7×2см, дебелина 3мм" },
      { src: `/Products/jewellery/Necklace Aurelius Cross/kolie-aurelius-cross-lifestyle.webp`,               alt: "Колие Aurelius Cross - лайфстайл снимка, носено на шия" },
      { src: `/Products/jewellery/Necklace Aurelius Cross/kolie-aurelius-cross-verizka-60cm.webp`,            alt: "Колие Aurelius Cross - детайл на верижката, дължина 60см" },
      { src: `/Products/jewellery/Necklace Aurelius Cross/kolie-aurelius-cross-karabiner.webp`,               alt: "Колие Aurelius Cross - детайл на карабинера, 750 IT печат" },
      { src: `/Products/jewellery/Necklace Aurelius Cross/kolie-aurelius-cross-kutiya.webp`,                  alt: "Колие Aurelius Cross в подаръчна кутия Lorenzo Ricci" },
    ],
  },
  {
    id: "necklace-grande-imperiale",
    slug: "necklace-grande-imperiale",
    sku: "KO-GRANDE-IMPERIALE",
    name: "Колие Grande Imperiale",
    category: "jewellery",
    subcategory: "necklace",
    price: 39,
    originalPrice: 62,
    currency: "€",
    badge: "Ограничена наличност",
    inStock: true,
    warranty: "Доживотна гаранция",
    shortDescription: "Италианска естетика в съвременна форма",
    description:
      "Grande Imperiale е символ на власт и изтънченост. Масивен кръст с размери 8.5 × 5 см на верижка с ширина 3 мм и дължина 60 см. 4-слойно 18K PVD покритие, което не избледнява. Устойчиво на вода, пот и парфюм. Хипоалергенно. Доживотна гаранция.",
    features: [
      "4-слойно 18K PVD златно покритие - не избледнява",
      "Масивен кръст 8.5 × 5 см - доминиращо присъствие",
      "Верижка 3 мм × 60 см",
      "Устойчиво на вода, пот и парфюм",
      "Хипоалергенна 316L неръждаема стомана",
      "Физически печат 'ITALY' - вграден символ на италианския дизайн",
    ],
    specs: [
      { label: "Материал", value: "316L неръждаема стомана с 18K PVD покритие" },
      { label: "Размер на кръста", value: "8.5 × 5 см" },
      { label: "Ширина на верижката", value: "3 мм" },
      { label: "Дължина", value: "60 см" },
      { label: "Покритие", value: "4-слойно 18K PVD златно" },
      { label: "Печат", value: "750 IT" },
    ],
    coverImage: {
      src: `/Products/jewellery/Necklace Grande Imperiale /kolie-grande-imperiale-18k-pvd-preden-izgled.webp`,
      alt: "Колие Grande Imperiale Lorenzo Ricci - масивен кръст 8.5×5см, 18K PVD позлата, 316L стомана",
    },
    images: [
      { src: `/Products/jewellery/Necklace Grande Imperiale /kolie-grande-imperiale-18k-pvd-preden-izgled.webp`, alt: "Колие Grande Imperiale Lorenzo Ricci - продуктова снимка бял фон, 18K PVD злато" },
      { src: `/Products/jewellery/Necklace Grande Imperiale /kolie-grande-imperiale-detal-masiven-krast.webp`,    alt: "Колие Grande Imperiale - детайл на масивния кръст, размери 8.5×5см" },
      { src: `/Products/jewellery/Necklace Grande Imperiale /kolie-grande-imperiale-lifestyle.webp`,               alt: "Колие Grande Imperiale - лайфстайл снимка, носено на шия" },
      { src: `/Products/jewellery/Necklace Grande Imperiale /kolie-grande-imperiale-verizka-60cm.webp`,            alt: "Колие Grande Imperiale - детайл на верижката 3мм, дължина 60см" },
      { src: `/Products/jewellery/Necklace Grande Imperiale /kolie-grande-imperiale-kutiya.webp`,                  alt: "Колие Grande Imperiale в подаръчна кутия Lorenzo Ricci" },
    ],
  },
  {
    id: "necklace-milano-forte",
    slug: "necklace-milano-forte",
    sku: "LA-MILANO-FORTE",
    name: "Колие Milano Forte",
    category: "jewellery",
    subcategory: "necklace",
    price: 37,
    originalPrice: 55,
    currency: "€",
    inStock: true,
    warranty: "Доживотна гаранция",
    shortDescription: "Италианска естетика в съвременна форма",
    description:
      "Колие Milano Forte носи тежестта на Милано - плътна плетена верижка с масивно присъствие и 18K PVD покритие. Устойчиво на вода, пот и парфюм. Хипоалергенно. Доживотна гаранция.",
    features: [
      "4-слойно 18K PVD златно покритие - не избледнява",
      "Масивна плетена верижка",
      "Устойчиво на вода, пот и парфюм",
      "Хипоалергенна 316L неръждаема стомана",
      "Физически печат 'ITALY' - вграден символ на италианския дизайн",
    ],
    specs: [
      { label: "Материал", value: "316L неръждаема стомана с 18K PVD покритие" },
      { label: "Покритие", value: "4-слойно 18K PVD златно" },
      { label: "Печат", value: "750 IT" },
    ],
    coverImage: {
      src: `/Products/jewellery/Necklace Milano Forte/kolie-milano-forte-18k-pvd-preden-izgled.webp`,
      alt: "Колие Milano Forte Lorenzo Ricci - масивна плетена верижка, 18K PVD позлата, 316L стомана",
    },
    images: [
      { src: `/Products/jewellery/Necklace Milano Forte/kolie-milano-forte-18k-pvd-preden-izgled.webp`, alt: "Колие Milano Forte Lorenzo Ricci - продуктова снимка бял фон, 18K PVD злато" },
      { src: `/Products/jewellery/Necklace Milano Forte/kolie-milano-forte-lifestyle.webp`,              alt: "Колие Milano Forte - лайфстайл снимка, носено на шия" },
      { src: `/Products/jewellery/Necklace Milano Forte/kolie-milano-forte-detal-masivna-pletka.webp`,   alt: "Колие Milano Forte - детайл на масивната плетена верижка" },
      { src: `/Products/jewellery/Necklace Milano Forte/kolie-milano-forte-karabiner.webp`,              alt: "Колие Milano Forte - детайл на карабинера, 750 IT печат" },
      { src: `/Products/jewellery/Necklace Milano Forte/kolie-milano-forte-kutiya.webp`,                 alt: "Колие Milano Forte в подаръчна кутия Lorenzo Ricci" },
    ],
  },
  {
    id: "necklace-milano-twist",
    slug: "necklace-milano-twist",
    sku: "KO-MILANO-TWIST",
    name: "Колие Milano Twist",
    category: "jewellery",
    subcategory: "necklace",
    price: 37,
    originalPrice: 51,
    currency: "€",
    inStock: true,
    warranty: "Доживотна гаранция",
    shortDescription: "Италианска естетика в съвременна форма",
    description:
      "Колие Milano Twist е усукана верижка с 18K PVD позлата - ширина 6 мм, дължина 55 см. Изчистена, елегантна, вечна. Устойчива на вода, пот и парфюм. Хипоалергенна. Доживотна гаранция.",
    features: [
      "4-слойно 18K PVD златно покритие - не избледнява",
      "Ширина 6 мм, дължина 55 см",
      "Усукана плетка - уникален характер",
      "Устойчиво на вода, пот и парфюм",
      "Хипоалергенна 316L неръждаема стомана",
    ],
    specs: [
      { label: "Материал", value: "316L неръждаема стомана с 18K PVD покритие" },
      { label: "Ширина", value: "6 мм" },
      { label: "Дължина", value: "55 см" },
      { label: "Покритие", value: "4-слойно 18K PVD златно" },
      { label: "Печат", value: "750 IT" },
    ],
    coverImage: {
      src: `/Products/jewellery/Necklace Milano Twist/kolie-milano-twist-18k-pvd-preden-izgled.webp`,
      alt: "Колие Milano Twist Lorenzo Ricci - усукана верижка 6мм, 18K PVD позлата, 316L стомана",
    },
    images: [
      { src: `/Products/jewellery/Necklace Milano Twist/kolie-milano-twist-18k-pvd-preden-izgled.webp`, alt: "Колие Milano Twist Lorenzo Ricci - продуктова снимка бял фон, 18K PVD злато" },
      { src: `/Products/jewellery/Necklace Milano Twist/kolie-milano-twist-lifestyle.webp`,               alt: "Колие Milano Twist - лайфстайл снимка, носено на шия" },
      { src: `/Products/jewellery/Necklace Milano Twist/kolie-milano-twist-detal-usukana-verizka.webp`,   alt: "Колие Milano Twist - детайл на усуканата верижка, ширина 6мм" },
      { src: `/Products/jewellery/Necklace Milano Twist/kolie-milano-twist-karabiner-55cm.webp`,          alt: "Колие Milano Twist - детайл на карабинера, дължина 55см" },
      { src: `/Products/jewellery/Necklace Milano Twist/kolie-milano-twist-blizak-plan.webp`,             alt: "Колие Milano Twist - близък план на плетката, 750 IT печат" },
      { src: `/Products/jewellery/Necklace Milano Twist/kolie-milano-twist-kutiya.webp`,                  alt: "Колие Milano Twist в подаръчна кутия Lorenzo Ricci" },
    ],
  },

  // ─── WALLETS ────────────────────────────────────────────────────────────────
  {
    id: "wallet-alabastro",
    slug: "wallet-alabastro",
    sku: "WLT-ALA",
    name: 'Lorenzo Ricci "Alabastro"',
    category: "wallets",
    price: 178,
    currency: "€",
    inStock: true,
    stock: 5,
    warranty: "2 години гаранция",
    shortDescription: "Бял портфейл от крокодилска кожа",
    description: 'Всяко изделие от линията на Lorenzo Ricci е израз на безкомпромисен лукс. Съчетаваме суровата елегантност на автентичната кожа от сиамски крокодил (Crocodylus siamensis) с прецизна градска функционалност за тези, които ценят строгата индивидуалност.',
    materialNote: 'Изработено от истинска крокодилска кожа. Тъй като всяка кожа е уникална, шарките и текстурата може да се различават леко от показаните на снимките - това е естествена характеристика на автентичната крокодилска кожа и придава на всяко изделие неповторим характер.',
    features: [
      "100% естествена крокодилска кожа - Crocodylus Siamensis",
      "CITES сертифициран произход №: 25VN4174/S",
      "Ръчна изработка - всяко изделие е уникално",
      "Луксозна подаръчна кутия с Сертификат за автентичност",
    ],
    specs: [
      { label: "Материал", value: "100% Крокодилска кожа" },
      { label: "Вид", value: "Crocodylus Siamensis" },
      { label: "CITES №", value: "25VN4174/S" },
      { label: "Изработка", value: "Ръчна" },
      { label: "Цвят", value: "Бял (Alabastro)" },
    ],
    coverImage: { src: `/Products/wallets/Alabastro/portfeil-alabastro-byal-krokodiilska-kozha.webp`, alt: 'Lorenzo Ricci Alabastro бял портфейл крокодилска кожа Crocodylus Siamensis - преден изглед' },
    images: [
      { src: `/Products/wallets/Alabastro/portfeil-alabastro-byal-krokodiilska-kozha.webp`,         alt: 'Lorenzo Ricci Alabastro бял портфейл крокодилска кожа - продуктова снимка' },
      { src: `/Products/wallets/Alabastro/portfeil-alabastro-detal-krokodiilska-tekstura.webp`,      alt: 'Lorenzo Ricci Alabastro - детайл на крокодилската текстура, Crocodylus Siamensis' },
      { src: `/Products/wallets/Alabastro/portfeil-alabastro-otvoren-vatreshnost.webp`,              alt: 'Lorenzo Ricci Alabastro - отворен портфейл, вътрешност с джобове за карти' },
      { src: `/Products/wallets/Alabastro/portfeil-alabastro-rachna-izrabotka.webp`,                 alt: 'Lorenzo Ricci Alabastro - детайл на ръчната изработка, прецизни шевове' },
      { src: `/Products/wallets/Alabastro/portfeil-alabastro-kutiya-sertifikat.webp`,                alt: 'Lorenzo Ricci Alabastro в луксозна кутия с Сертификат за автентичност CITES' },
    ],
  },
  {
    id: "wallet-rubino",
    slug: "wallet-rubino",
    sku: "WLT-RUB",
    name: 'Lorenzo Ricci "Rubino"',
    category: "wallets",
    price: 178,
    currency: "€",
    inStock: true,
    stock: 5,
    warranty: "2 години гаранция",
    shortDescription: "Червен портфейл от крокодилска кожа",
    description: 'Всяко изделие от линията на Lorenzo Ricci е израз на безкомпромисен лукс. Съчетаваме суровата елегантност на автентичната кожа от сиамски крокодил (Crocodylus siamensis) с прецизна градска функционалност за тези, които ценят строгата индивидуалност.',
    materialNote: 'Изработено от истинска крокодилска кожа. Тъй като всяка кожа е уникална, шарките и текстурата може да се различават леко от показаните на снимките - това е естествена характеристика на автентичната крокодилска кожа и придава на всяко изделие неповторим характер.',
    features: [
      "100% естествена крокодилска кожа - Crocodylus Siamensis",
      "CITES сертифициран произход №: 25VN4174/S",
      "Ръчна изработка - всяко изделие е уникално",
      "Луксозна подаръчна кутия с Сертификат за автентичност",
    ],
    specs: [
      { label: "Материал", value: "100% Крокодилска кожа" },
      { label: "Вид", value: "Crocodylus Siamensis" },
      { label: "CITES №", value: "25VN4174/S" },
      { label: "Изработка", value: "Ръчна" },
      { label: "Цвят", value: "Рубинено червен (Rubino)" },
    ],
    coverImage: { src: `/Products/wallets/Rubino/portfeil-rubino-cherven-krokodiilska-kozha.webp`, alt: 'Lorenzo Ricci Rubino червен портфейл крокодилска кожа Crocodylus Siamensis - преден изглед' },
    images: [
      { src: `/Products/wallets/Rubino/portfeil-rubino-cherven-krokodiilska-kozha.webp`,        alt: 'Lorenzo Ricci Rubino червен портфейл крокодилска кожа - продуктова снимка' },
      { src: `/Products/wallets/Rubino/portfeil-rubino-detal-krokodiilska-tekstura.webp`,        alt: 'Lorenzo Ricci Rubino - детайл на крокодилската текстура, рубинено червено' },
      { src: `/Products/wallets/Rubino/portfeil-rubino-otvoren-vatreshnost.webp`,                alt: 'Lorenzo Ricci Rubino - отворен портфейл, вътрешност с джобове за карти' },
      { src: `/Products/wallets/Rubino/portfeil-rubino-rachna-izrabotka.webp`,                   alt: 'Lorenzo Ricci Rubino - детайл на ръчната изработка, прецизни шевове' },
      { src: `/Products/wallets/Rubino/portfeil-rubino-kutiya-sertifikat.webp`,                  alt: 'Lorenzo Ricci Rubino в луксозна кутия с Сертификат за автентичност CITES' },
    ],
  },
  {
    id: "wallet-smeraldo",
    slug: "wallet-smeraldo",
    sku: "WLT-SME",
    name: 'Lorenzo Ricci "Smeraldo"',
    category: "wallets",
    price: 178,
    currency: "€",
    badge: "Изчерпан",
    inStock: false,
    stock: 0,
    warranty: "2 години гаранция",
    shortDescription: "Зелен портфейл от крокодилска кожа",
    description: 'Всяко изделие от линията на Lorenzo Ricci е израз на безкомпромисен лукс. Съчетаваме суровата елегантност на автентичната кожа от сиамски крокодил (Crocodylus siamensis) с прецизна градска функционалност за тези, които ценят строгата индивидуалност.',
    materialNote: 'Изработено от истинска крокодилска кожа. Тъй като всяка кожа е уникална, шарките и текстурата може да се различават леко от показаните на снимките - това е естествена характеристика на автентичната крокодилска кожа и придава на всяко изделие неповторим характер.',
    features: [
      "100% естествена крокодилска кожа - Crocodylus Siamensis",
      "CITES сертифициран произход №: 25VN4174/S",
      "Ръчна изработка - всяко изделие е уникално",
      "Луксозна подаръчна кутия с Сертификат за автентичност",
    ],
    specs: [
      { label: "Материал", value: "100% Крокодилска кожа" },
      { label: "Вид", value: "Crocodylus Siamensis" },
      { label: "CITES №", value: "25VN4174/S" },
      { label: "Изработка", value: "Ръчна" },
      { label: "Цвят", value: "Изумруденозелен (Smeraldo)" },
    ],
    coverImage: { src: `/Products/wallets/Smeraldo/portfeil-smeraldo-zelen-krokodiilska-kozha.webp`, alt: 'Lorenzo Ricci Smeraldo зелен портфейл крокодилска кожа Crocodylus Siamensis - преден изглед' },
    images: [
      { src: `/Products/wallets/Smeraldo/portfeil-smeraldo-zelen-krokodiilska-kozha.webp`,        alt: 'Lorenzo Ricci Smeraldo зелен портфейл крокодилска кожа - продуктова снимка' },
      { src: `/Products/wallets/Smeraldo/portfeil-smeraldo-detal-krokodiilska-tekstura.webp`,      alt: 'Lorenzo Ricci Smeraldo - детайл на крокодилската текстура, изумруденозелено' },
      { src: `/Products/wallets/Smeraldo/portfeil-smeraldo-otvoren-vatreshnost.webp`,              alt: 'Lorenzo Ricci Smeraldo - отворен портфейл, вътрешност с джобове за карти' },
      { src: `/Products/wallets/Smeraldo/portfeil-smeraldo-rachna-izrabotka.webp`,                 alt: 'Lorenzo Ricci Smeraldo - детайл на ръчната изработка, прецизни шевове' },
      { src: `/Products/wallets/Smeraldo/portfeil-smeraldo-kutiya-sertifikat.webp`,                alt: 'Lorenzo Ricci Smeraldo в луксозна кутия с Сертификат за автентичност CITES' },
    ],
  },

  // ─── CARDHOLDERS ────────────────────────────────────────────────────────────
  {
    id: "cardholder-ambra",
    slug: "cardholder-ambra",
    sku: "CRD-AMB",
    name: 'Lorenzo Ricci "Ambra"',
    category: "cardholders",
    price: 65,
    currency: "€",
    inStock: true,
    stock: 15,
    warranty: "2 години гаранция",
    shortDescription: "Оранжев кардхолдър от крокодилска кожа",
    description: 'Всяко изделие от линията на Lorenzo Ricci е израз на безкомпромисен лукс. Съчетаваме суровата елегантност на автентичната кожа от сиамски крокодил (Crocodylus siamensis) с прецизна градска функционалност за тези, които ценят строгата индивидуалност.',
    materialNote: 'Изработено от истинска крокодилска кожа. Тъй като всяка кожа е уникална, шарките и текстурата може да се различават леко от показаните на снимките - това е естествена характеристика на автентичната крокодилска кожа и придава на всяко изделие неповторим характер.',
    features: [
      "100% естествена крокодилска кожа - Crocodylus Siamensis",
      "CITES сертифициран произход №: 25VN4174/S",
      "Ръчна изработка - всяко изделие е уникално",
      "Луксозна подаръчна кутия с Сертификат за автентичност",
    ],
    specs: [
      { label: "Материал", value: "100% Крокодилска кожа" },
      { label: "Вид", value: "Crocodylus Siamensis" },
      { label: "CITES №", value: "25VN4174/S" },
      { label: "Изработка", value: "Ръчна" },
      { label: "Цвят", value: "Кехлибарено оранжев (Ambra)" },
    ],
    coverImage: { src: `/Products/wallets/Ambra/kardholder-ambra-oranjev-krokodiilska-kozha.webp`, alt: 'Lorenzo Ricci Ambra оранжев кардхолдър крокодилска кожа Crocodylus Siamensis - преден изглед' },
    images: [
      { src: `/Products/wallets/Ambra/kardholder-ambra-oranjev-krokodiilska-kozha.webp`,      alt: 'Lorenzo Ricci Ambra оранжев кардхолдър крокодилска кожа - продуктова снимка' },
      { src: `/Products/wallets/Ambra/kardholder-ambra-detal-krokodiilska-tekstura.webp`,     alt: 'Lorenzo Ricci Ambra - детайл на крокодилската текстура, кехлибарено оранжево' },
      { src: `/Products/wallets/Ambra/kardholder-ambra-lifestyle.webp`,                       alt: 'Lorenzo Ricci Ambra кардхолдър - лайфстайл снимка, ежедневна употреба' },
      { src: `/Products/wallets/Ambra/kardholder-ambra-kutiya-sertifikat.webp`,               alt: 'Lorenzo Ricci Ambra в луксозна кутия с Сертификат за автентичност CITES' },
    ],
  },
  {
    id: "cardholder-bianco",
    slug: "cardholder-bianco",
    sku: "CRD-BIA",
    name: 'Lorenzo Ricci "Bianco"',
    category: "cardholders",
    price: 65,
    currency: "€",
    inStock: true,
    stock: 15,
    warranty: "2 години гаранция",
    shortDescription: "Бял кожен кардхолдър",
    description: 'Всяко изделие от линията на Lorenzo Ricci е израз на безкомпромисен лукс. Съчетаваме суровата елегантност на автентичната кожа от сиамски крокодил (Crocodylus siamensis) с прецизна градска функционалност за тези, които ценят строгата индивидуалност.',
    materialNote: 'Изработено от истинска крокодилска кожа. Тъй като всяка кожа е уникална, шарките и текстурата може да се различават леко от показаните на снимките - това е естествена характеристика на автентичната крокодилска кожа и придава на всяко изделие неповторим характер.',
    features: [
      "100% естествена крокодилска кожа - Crocodylus Siamensis",
      "CITES сертифициран произход №: 25VN4174/S",
      "Ръчна изработка - всяко изделие е уникално",
      "Луксозна подаръчна кутия с Сертификат за автентичност",
    ],
    specs: [
      { label: "Материал", value: "100% Крокодилска кожа" },
      { label: "Вид", value: "Crocodylus Siamensis" },
      { label: "CITES №", value: "25VN4174/S" },
      { label: "Изработка", value: "Ръчна" },
      { label: "Цвят", value: "Бял (Bianco)" },
    ],
    coverImage: { src: `/Products/wallets/Bianco/kardholder-bianco-byal-krokodiilska-kozha.webp`, alt: 'Lorenzo Ricci Bianco бял кардхолдър крокодилска кожа Crocodylus Siamensis - преден изглед' },
    images: [
      { src: `/Products/wallets/Bianco/kardholder-bianco-byal-krokodiilska-kozha.webp`,       alt: 'Lorenzo Ricci Bianco бял кардхолдър крокодилска кожа - продуктова снимка' },
      { src: `/Products/wallets/Bianco/kardholder-bianco-detal-krokodiilska-tekstura.webp`,    alt: 'Lorenzo Ricci Bianco - детайл на крокодилската текстура, бял цвят' },
      { src: `/Products/wallets/Bianco/kardholder-bianco-lifestyle.webp`,                      alt: 'Lorenzo Ricci Bianco кардхолдър - лайфстайл снимка, ежедневна употреба' },
      { src: `/Products/wallets/Bianco/kardholder-bianco-kutiya-sertifikat.webp`,              alt: 'Lorenzo Ricci Bianco в луксозна кутия с Сертификат за автентичност CITES' },
    ],
  },
  {
    id: "cardholder-valentina",
    slug: "cardholder-valentina",
    sku: "CRD-VAL",
    name: 'Lorenzo Ricci "Valentina"',
    category: "cardholders",
    price: 65,
    currency: "€",
    inStock: true,
    stock: 15,
    warranty: "2 години гаранция",
    shortDescription: "Розов кардхолдър от крокодилска кожа",
    description: 'Всяко изделие от линията на Lorenzo Ricci е израз на безкомпромисен лукс. Съчетаваме суровата елегантност на автентичната кожа от сиамски крокодил (Crocodylus siamensis) с прецизна градска функционалност за тези, които ценят строгата индивидуалност.',
    materialNote: 'Изработено от истинска крокодилска кожа. Тъй като всяка кожа е уникална, шарките и текстурата може да се различават леко от показаните на снимките - това е естествена характеристика на автентичната крокодилска кожа и придава на всяко изделие неповторим характер.',
    features: [
      "100% естествена крокодилска кожа - Crocodylus Siamensis",
      "CITES сертифициран произход №: 25VN4174/S",
      "Ръчна изработка - всяко изделие е уникално",
      "Луксозна подаръчна кутия с Сертификат за автентичност",
    ],
    specs: [
      { label: "Материал", value: "100% Крокодилска кожа" },
      { label: "Вид", value: "Crocodylus Siamensis" },
      { label: "CITES №", value: "25VN4174/S" },
      { label: "Изработка", value: "Ръчна" },
      { label: "Цвят", value: "Розов (Valentina)" },
    ],
    coverImage: { src: `/Products/wallets/Valentina/kardholder-valentina-rozov-krokodiilska-kozha.webp`, alt: 'Lorenzo Ricci Valentina розов кардхолдър крокодилска кожа Crocodylus Siamensis - преден изглед' },
    images: [
      { src: `/Products/wallets/Valentina/kardholder-valentina-rozov-krokodiilska-kozha.webp`,      alt: 'Lorenzo Ricci Valentina розов кардхолдър крокодилска кожа - продуктова снимка' },
      { src: `/Products/wallets/Valentina/kardholder-valentina-detal-krokodiilska-tekstura.webp`,    alt: 'Lorenzo Ricci Valentina - детайл на крокодилската текстура, розов цвят' },
      { src: `/Products/wallets/Valentina/kardholder-valentina-lifestyle.webp`,                      alt: 'Lorenzo Ricci Valentina кардхолдър - лайфстайл снимка, ежедневна употреба' },
      { src: `/Products/wallets/Valentina/kardholder-valentina-kutiya-sertifikat.webp`,              alt: 'Lorenzo Ricci Valentina в луксозна кутия с Сертификат за автентичност CITES' },
    ],
  },
  {
    id: "cardholder-zaffiro",
    slug: "cardholder-zaffiro",
    sku: "CRD-ZAF",
    name: 'Lorenzo Ricci "Zaffiro"',
    category: "cardholders",
    price: 65,
    currency: "€",
    inStock: true,
    stock: 15,
    warranty: "2 години гаранция",
    shortDescription: "Тъмносин кардхолдър от крокодилска кожа",
    description: 'Всяко изделие от линията на Lorenzo Ricci е израз на безкомпромисен лукс. Съчетаваме суровата елегантност на автентичната кожа от сиамски крокодил (Crocodylus siamensis) с прецизна градска функционалност за тези, които ценят строгата индивидуалност.',
    materialNote: 'Изработено от истинска крокодилска кожа. Тъй като всяка кожа е уникална, шарките и текстурата може да се различават леко от показаните на снимките - това е естествена характеристика на автентичната крокодилска кожа и придава на всяко изделие неповторим характер.',
    features: [
      "100% естествена крокодилска кожа - Crocodylus Siamensis",
      "CITES сертифициран произход №: 25VN4174/S",
      "Ръчна изработка - всяко изделие е уникално",
      "Луксозна подаръчна кутия с Сертификат за автентичност",
    ],
    specs: [
      { label: "Материал", value: "100% Крокодилска кожа" },
      { label: "Вид", value: "Crocodylus Siamensis" },
      { label: "CITES №", value: "25VN4174/S" },
      { label: "Изработка", value: "Ръчна" },
      { label: "Цвят", value: "Сапфирено син (Zaffiro)" },
    ],
    coverImage: { src: `/Products/wallets/Zaffiro/kardholder-zaffiro-sinen-krokodiilska-kozha.webp`, alt: 'Lorenzo Ricci Zaffiro тъмносин кардхолдър крокодилска кожа Crocodylus Siamensis - преден изглед' },
    images: [
      { src: `/Products/wallets/Zaffiro/kardholder-zaffiro-sinen-krokodiilska-kozha.webp`,       alt: 'Lorenzo Ricci Zaffiro тъмносин кардхолдър крокодилска кожа - продуктова снимка' },
      { src: `/Products/wallets/Zaffiro/kardholder-zaffiro-detal-krokodiilska-tekstura.webp`,     alt: 'Lorenzo Ricci Zaffiro - детайл на крокодилската текстура, сапфирено синьо' },
      { src: `/Products/wallets/Zaffiro/kardholder-zaffiro-lifestyle.webp`,                       alt: 'Lorenzo Ricci Zaffiro кардхолдър - лайфстайл снимка, ежедневна употреба' },
      { src: `/Products/wallets/Zaffiro/kardholder-zaffiro-kutiya-sertifikat.webp`,               alt: 'Lorenzo Ricci Zaffiro в луксозна кутия с Сертификат за автентичност CITES' },
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getWatches(): Product[] {
  return products.filter((p) => p.category === "watches");
}

export function getJewellery(): Product[] {
  return products.filter((p) => p.category === "jewellery");
}

export function getBracelets(): Product[] {
  return products.filter((p) => p.subcategory === "bracelet");
}

export function getNecklaces(): Product[] {
  return products.filter((p) => p.subcategory === "necklace");
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}
