import type { Review } from "./types";

export const reviews: Review[] = [

  // ─── CHRONO BLACK ───────────────────────────────────────────────────────────
  {
    id: "r-1",
    productSlug: "chrono-black",
    author: "Петър К.",
    rating: 5,
    body: "Носих го на сватба и веднага направи впечатление. Много класически и изчистен дизайн.",
    date: "2026-04-12",
  },
  {
    id: "r-2",
    productSlug: "chrono-black",
    author: "Яна С.",
    rating: 5,
    body: "Купих го като подарък за съпруга ми и той е много доволен. Носи го всеки ден на работа. Кутията е много луксозна.",
    imageUrl: "/reviews/chrono-black-yana.jpg",
    date: "2026-04-11",
  },
  {
    id: "r-4",
    productSlug: "chrono-black",
    author: "Едуард В.",
    rating: 5,
    body: "Има много сериозен и стилен вид. Тежи приятно на ръката.",
    date: "2026-02-14",
  },
  {
    id: "r-5",
    productSlug: "chrono-black",
    author: "Георги Б.",
    rating: 5,
    body: "Красив е. Наистина много добро изпълнение. От висококачествена неръждаема стомана е, тежи приятно на ръката и се усеща стабилен, не като кухите евтини модели. Механизмът върви плавно",
    imageUrl: "/reviews/chrono-black-Георги.webp",
    date: "2026-05-28",
  },
  {
    id: "r-6",
    productSlug: "chrono-black",
    author: "Павел В.",
    rating: 5,
    date: "2025-12-08",
  },
  {
    id: "r-8",
    productSlug: "chrono-black",
    author: "Еди М.",
    rating: 5,
    body: "Аз съм с малка китка 16 см и имах притеснения дали ще ми стане. Обаче ми заспа.",
    imageUrl: "/reviews/chrono-black-Еди.webp",
    date: "2026-06-03",
  },
  {
    id: "r-10",
    productSlug: "chrono-black",
    author: "Тодор Г.",
    rating: 5,
    body: "Прецизен механизъм, стъклото е кристално чисто. Препоръчвам.",
    date: "2025-07-11",
  },
  {
    id: "r-11",
    productSlug: "chrono-black",
    author: "Андрей В.",
    rating: 5,
    body: "Купих го след дълго колебание и не съжалявам. Носи се комфортно, вижда се отдалеч.",
    date: "2025-05-30",
  },
  {
    id: "r-12",
    productSlug: "chrono-black",
    author: "Христо В.",
    rating: 5,
    body: "По-тежък е на ръка отколкото очаквах от снимките. Хубава изненада.",
    date: "2025-04-17",
  },
  {
    id: "r-13",
    productSlug: "chrono-black",
    author: "Димитър Н.",
    rating: 5,
    body: "Носих го на Нова година, три пъти ме попитаха откъде е.",
    date: "2025-03-02",
  },
  {
    id: "r-14",
    productSlug: "chrono-black",
    author: "Николай Б.",
    rating: 4,
    body: "Каишката може да се смени с кожена за по-официален вид. Иначе стои много добре.",
    date: "2025-01-25",
  },

  // ─── GOLDEN ECLIPSE ─────────────────────────────────────────────────────────
  {
    id: "r-15",
    productSlug: "golden-eclipse",
    author: "Петър С.",
    rating: 5,
    title: "Класен е",
    body: "По принцип нося марки за хиляди левове, но реших да му дам шанс. Честно казано го заглеждат повече дори и от Rolex-ите ми, които имам.",
    imageUrl: "/reviews/golden-eclipse-ПетърС.webp",
    date: "2026-05-03",
  },
  {
    id: "r-150",
    productSlug: "golden-eclipse",
    author: "Христо П.",
    rating: 5,
    body: "Нося го на всяка официална среща. Много елегантен и изпипан модел.",
    imageUrl: "/reviews/golden-eclipse-AdrianF.webp",
    date: "2026-02-14",
  },
  {
    id: "r-151",
    productSlug: "golden-eclipse",
    author: "Стефан К.",
    rating: 5,
    body: "Часовникът е просто уникален. Но кутията също ме впечатли. Тежка, лъскав пиано лак в черно и чисто отпечатано Lorenzo Ricci отвътре. Единствено гланцът събира отпечатъци, но с микрофибърна кърпа става като нова за секунди.",
    imageUrl: "/reviews/golden-eclipse-EliasThatcher.webp",
    date: "2025-12-20",
  },
  {
    id: "r-152",
    productSlug: "golden-eclipse",
    author: "Ивайло М.",
    rating: 5,
    body: "Перфектен за официални поводи. Каишката е удобна и не дразни кожата. Много доволен.",
    imageUrl: "/reviews/golden-eclipse-FerencD.webp",
    date: "2025-10-05",
  },
  {
    id: "r-153",
    productSlug: "golden-eclipse",
    author: "Калоян В.",
    rating: 5,
    body: "Придава много завършен вид на костюма. Хронографът работи много плавно.",
    imageUrl: "/reviews/golden-eclipse-RainerD.webp",
    date: "2025-08-18",
  },
  {
    id: "r-154",
    productSlug: "golden-eclipse",
    author: "Мартин Г.",
    rating: 5,
    body: "Страхотна покупка. Японският механизъм работи безупречно. Доволен съм.",
    imageUrl: "/reviews/golden-eclipse-RolandasS.webp",
    date: "2025-06-12",
  },
  {
    id: "r-155",
    productSlug: "golden-eclipse",
    author: "Тихомир Д.",
    rating: 5,
    body: "Златният корпус добавя истинска класа. Изглежда страхотно и на ежедневно облекло.",
    imageUrl: "/reviews/golden-eclipse-TamasG.webp",
    date: "2025-04-03",
  },
  {
    id: "r-24",
    productSlug: "golden-eclipse",
    author: "Стоян Г.",
    rating: 5,
    body: "Купих го за 40-ия си рожден ден. Месец по-късно пак ми харесва, което не е малко.",
    date: "2025-02-20",
  },
  {
    id: "r-156",
    productSlug: "golden-eclipse",
    author: "Иван К.",
    rating: 5,
    body: "На три коледни тържества го носих и три пъти ме питаха откъде е.",
    date: "2025-01-15",
  },
  {
    id: "r-157",
    productSlug: "golden-eclipse",
    author: "Красимир Н.",
    rating: 5,
    body: "Не очаквах много. Тежестта и прецизността на живо ме изненадаха.",
    date: "2024-11-20",
  },
  {
    id: "r-158",
    productSlug: "golden-eclipse",
    author: "Добрин П.",
    rating: 5,
    body: "Изглежда отлично на ръката. Хронографът работи плавно и прецизно.",
    date: "2024-10-08",
  },
  {
    id: "r-159",
    productSlug: "golden-eclipse",
    author: "Кирил М.",
    rating: 5,
    body: "Сапфиреното стъкло е без надраскване след месеци носене. Качеството е видно.",
    date: "2024-08-22",
  },
  {
    id: "r-160",
    productSlug: "golden-eclipse",
    author: "Велизар Г.",
    rating: 5,
    date: "2024-08-01",
  },
  {
    id: "r-161",
    productSlug: "golden-eclipse",
    author: "Пламен Й.",
    rating: 5,
    body: "Три месеца ежедневно. Комплименти дори от хора, които не обичат часовници.",
    date: "2024-07-15",
  },
  {
    id: "r-162",
    productSlug: "golden-eclipse",
    author: "Светослав В.",
    rating: 5,
    body: "Точно като на снимките, може малко по-тежък. Приятна изненада.",
    date: "2024-06-28",
  },

  // ─── POLAR FROST ────────────────────────────────────────────────────────────
  {
    id: "r-25",
    productSlug: "polar-frost",
    author: "Атила С.",
    rating: 5,
    title: "Издържа на вода",
    body: "Воден е. Цяло лято бях на море с него и нямах проблеми. Изработен е от висококачествени материали, а не като китайските боклуци от сплав.",
    imageUrl: "/reviews/polar-frost-АтилаСемн.webp",
    date: "2026-05-17",
  },
  {
    id: "r-26",
    productSlug: "polar-frost",
    author: "Борис Н.",
    rating: 5,
    body: "Синьото ми е любим цвят, затова купих синия. Не го свалям от ръката си. Засега съм доволен.",
    imageUrl: "/reviews/boris-review.webp",
    date: "2026-04-22",
  },
  {
    id: "r-29",
    productSlug: "polar-frost",
    author: "Герхард Ц.",
    rating: 5,
    body: "Много хубав часовник, стъклото е отлично. Носих го на плаж и в басейн без никакъв проблем.",
    imageUrl: "/reviews/polar-frost-GerhardC.webp",
    date: "2025-10-31",
  },
  {
    id: "r-31",
    productSlug: "polar-frost",
    author: "Кирил Д.",
    rating: 5,
    body: "Купих го след като видях снимки и не съжалявам. На живо изглежда много по-хубав отколкото на снимки.",
    date: "2025-06-28",
  },
  {
    id: "r-32",
    productSlug: "polar-frost",
    author: "Ивайло Г.",
    rating: 4,
    body: "Часовникът е по-тежък отколкото очаквах, но се свиква след няколко носения.",
    date: "2025-03-14",
  },

  // ─── BRACELET DIAMANTE CROSS ─────────────────────────────────────────────────
  {
    id: "r-33",
    productSlug: "bracelet-diamante-cross",
    author: "Живко П.",
    rating: 5,
    body: "Стои много добре на китката и изглежда доста елегантно. Камъчетата добавят хубав блясък без да е прекалено.",
    imageUrl: "/reviews/bracelet-diamante-cross-ЖивкоП.webp",
    date: "2026-04-28",
  },
  {
    id: "r-34",
    productSlug: "bracelet-diamante-cross",
    author: "Борислав К.",
    rating: 5,
    body: "Когато я извадих от кутията ми направи впечатление колко чисто е направен кръстът. Много красив модел.",
    imageUrl: "/reviews/bracelet-diamante-cross-БориславК.webp",
    date: "2026-03-19",
  },
  {
    id: "r-35",
    productSlug: "bracelet-diamante-cross",
    author: "Стефан Ц.",
    rating: 4,
    body: "Окей е. Очаквах да е малко по-дебела, но стои добре на китката и се вижда хубаво.",
    imageUrl: "/reviews/bracelet-diamante-cross-СтефанЦ.webp",
    date: "2026-02-07",
  },
  {
    id: "r-36",
    productSlug: "bracelet-diamante-cross",
    author: "Анелия С.",
    rating: 5,
    body: "Купих я за приятеля ми и той е много доволен. Кутията е много елегантна, направо за подарък.",
    imageUrl: "/reviews/bracelet-diamante-cross-АнелияС.webp",
    date: "2025-12-24",
  },
  {
    id: "r-37",
    productSlug: "bracelet-diamante-cross",
    author: "Златомир Н.",
    rating: 5,
    body: "Стои страхотно до часовник. 18K позлатата изглежда много качествена, не е евтина.",
    imageUrl: "/reviews/bracelet-diamante-cross-ЗлатомирН.webp",
    date: "2025-10-06",
  },
  {
    id: "r-38",
    productSlug: "bracelet-diamante-cross",
    author: "Христо В.",
    rating: 5,
    body: "Нося я вече 2 месеца всеки ден. Не избледнява, не се надрасква.",
    date: "2025-07-18",
  },
  {
    id: "r-71",
    productSlug: "bracelet-diamante-cross",
    author: "Тодор А.",
    rating: 5,
    body: "Носих я още първия ден и получих комплимент.",
    date: "2026-02-23",
  },
  {
    id: "r-72",
    productSlug: "bracelet-diamante-cross",
    author: "Камен Г.",
    rating: 5,
    body: "Стои много добре до часовник. Кръстът придава различен характер на гривната.",
    date: "2026-02-21",
  },
  {
    id: "r-73",
    productSlug: "bracelet-diamante-cross",
    author: "Илия Р.",
    rating: 2,
    body: "Пратката се забави.",
    date: "2026-02-19",
  },
  {
    id: "r-74",
    productSlug: "bracelet-diamante-cross",
    author: "Александър В.",
    rating: 5,
    body: "Камъните блещукат на слънце, но не изглеждат евтино. Нося я и на работа.",
    date: "2026-02-17",
  },
  {
    id: "r-75",
    productSlug: "bracelet-diamante-cross",
    author: "Мирослав Б.",
    rating: 4,
    body: "Носи се удобно през целия ден. Не усещам да пречи или да дразни.",
    date: "2026-02-16",
  },
  {
    id: "r-76",
    productSlug: "bracelet-diamante-cross",
    author: "Явор Ж.",
    rating: 5,
    body: "С голяма китка съм 23 см, но се регулира. Стана ми. Трудно намирам бижута и часовници за размера ми. Доволен съм.",
    date: "2026-02-13",
  },
  {
    id: "r-77",
    productSlug: "bracelet-diamante-cross",
    author: "Никола Ч.",
    rating: 5,
    date: "2026-02-12",
  },
  {
    id: "r-78",
    productSlug: "bracelet-diamante-cross",
    author: "Георги Т.",
    rating: 5,
    body: "Купих я на майка ми понеже е набожна. Хареса й.",
    date: "2026-02-11",
  },
  {
    id: "r-79",
    productSlug: "bracelet-diamante-cross",
    author: "Радослав Л.",
    rating: 5,
    body: "Подарих я за именен ден. Хареса много повече от очакваното.",
    date: "2026-02-10",
  },
  {
    id: "r-80",
    productSlug: "bracelet-diamante-cross",
    author: "Емил С.",
    rating: 5,
    body: "Камъните са в точния размер, не крещят. Исках блясък без кич.",
    date: "2026-02-09",
  },
  {
    id: "r-81",
    productSlug: "bracelet-diamante-cross",
    author: "Христо Я.",
    rating: 5,
    body: "Моля пуснете модел със зелени камъни! Много харесвам тази гривна.",
    date: "2026-02-08",
  },
  {
    id: "r-82",
    productSlug: "bracelet-diamante-cross",
    author: "Людмил Х.",
    rating: 5,
    body: "Личи си, че дизайнът е мислен. Не изглежда като масов модел.",
    date: "2026-02-06",
  },
  {
    id: "r-83",
    productSlug: "bracelet-diamante-cross",
    author: "Даниел М.",
    rating: 5,
    body: "Рядко пиша коментари. Няма какво да се чудите, гривната е страхотна.",
    date: "2026-02-05",
  },

  // ─── BRACELET DIAMANTE CROSS — допълнителни текстови ────────────────────────
  {
    id: "r-350",
    productSlug: "bracelet-diamante-cross",
    author: "Пламен И.",
    rating: 5,
    body: "Взех за приятел. Казаха му на работа, че изглежда добре, на първия ден.",
    date: "2026-04-11",
  },
  {
    id: "r-351",
    productSlug: "bracelet-diamante-cross",
    author: "Валентин Д.",
    rating: 5,
    body: "Нося я с черен часовник. Кръстът я прави различна от обичайните.",
    date: "2026-03-14",
  },
  {
    id: "r-352",
    productSlug: "bracelet-diamante-cross",
    author: "Деян П.",
    rating: 5,
    body: "От първото слагане стои като ушита. Не очаквах да се усеща толкова естествено.",
    date: "2025-10-20",
  },
  {
    id: "r-353",
    productSlug: "bracelet-diamante-cross",
    author: "Стефан М.",
    rating: 5,
    body: "Кръстът е по-масивен на живо. Ръбовете са изчистени.",
    date: "2025-09-10",
  },

  // ─── BRACELET MILANO FORTE ──────────────────────────────────────────────────
  {
    id: "r-39",
    productSlug: "bracelet-milano-forte",
    author: "Александър Д.",
    rating: 5,
    body: "Масивна и хубава гривна. Стои много добре до часовник. Ширината е точно каквото исках.",
    imageUrl: "/reviews/bracelet-milano-forte-АлександърД.webp",
    date: "2026-05-11",
  },
  {
    id: "r-40",
    productSlug: "bracelet-milano-forte",
    author: "Георги К.",
    rating: 5,
    body: "Страхотна покупка! Тежи приятно и изглежда солидно. Получих я за 1 работен ден.",
    imageUrl: "/reviews/bracelet-milano-forte-ГеоргиК.webp",
    date: "2026-04-02",
  },
  {
    id: "r-41",
    productSlug: "bracelet-milano-forte",
    author: "Емил Д.",
    rating: 5,
    body: "Много масивна за цената. Позлатата е равномерна и хубава. Носил съм я в морето без проблем.",
    imageUrl: "/reviews/bracelet-milano-forte-ЕмилД.webp",
    date: "2026-02-25",
  },
  {
    id: "r-43",
    productSlug: "bracelet-milano-forte",
    author: "Мартин Г.",
    rating: 4,
    body: "Гривната е хубава и масивна. Закопчалката работи добре. Само опаковката можеше да е малко по-голяма.",
    imageUrl: "/reviews/bracelet-milano-forte-МартинГ.webp",
    date: "2025-09-30",
  },
  {
    id: "r-44",
    productSlug: "bracelet-milano-forte",
    author: "Стоян К.",
    rating: 5,
    body: "Много добра гривна. Взех я след дълго търсене и съм много доволен. Стои перфектно до часовник.",
    imageUrl: "/reviews/bracelet-milano-forte-СтоянК.webp",
    date: "2025-07-05",
  },

  // ─── BRACELET MILANO FORTE — допълнителни текстови ─────────────────────────
  {
    id: "r-300",
    productSlug: "bracelet-milano-forte",
    author: "Димитър П.",
    rating: 5,
    body: "Комбинирам я с часовник и визията се получава много добре.",
    date: "2026-04-24",
  },
  {
    id: "r-301",
    productSlug: "bracelet-milano-forte",
    author: "Николай В.",
    rating: 5,
    body: "Тежи приятно. По-леките гривни не ги усещам, тази я усещам.",
    date: "2026-04-11",
  },
  {
    id: "r-302",
    productSlug: "bracelet-milano-forte",
    author: "Петър С.",
    rating: 5,
    body: "Цветът е точно тъмното злато, което търсех. Получих комплимент при първото носене.",
    date: "2026-04-04",
  },
  {
    id: "r-303",
    productSlug: "bracelet-milano-forte",
    author: "Виктор Т.",
    rating: 5,
    body: "Носих я на плаж. Нямах нужда да я сваля и без проблеми с кожата.",
    date: "2026-03-17",
  },
  {
    id: "r-304",
    productSlug: "bracelet-milano-forte",
    author: "Борис Н.",
    rating: 4,
    body: "По-масивна е от снимките. Тежи приятно, не е лека и куха.",
    date: "2026-02-27",
  },
  {
    id: "r-305",
    productSlug: "bracelet-milano-forte",
    author: "Калоян М.",
    rating: 3,
    body: "На живо изглежда по-добре от снимките. Звената са равномерни.",
    date: "2026-01-08",
  },
  {
    id: "r-306",
    productSlug: "bracelet-milano-forte",
    author: "Радослав И.",
    rating: 4,
    body: "По-масивна е от Signature, но без да е прекалена. Търсех нещо между двете.",
    date: "2025-12-15",
  },
  {
    id: "r-307",
    productSlug: "bracelet-milano-forte",
    author: "Кристиан П.",
    rating: 5,
    body: "Три месеца, включително на басейн. Цветът е непроменен.",
    date: "2025-12-10",
  },
  {
    id: "r-308",
    productSlug: "bracelet-milano-forte",
    author: "Даниел С.",
    rating: 5,
    body: "Качеството се усеща веднага щом я сложиш. Няма усещане за евтин продукт.",
    date: "2025-11-20",
  },

  // ─── BRACELET MILANO TWIST ──────────────────────────────────────────────────
  {
    id: "r-45",
    productSlug: "bracelet-milano-twist",
    author: "Виктор П.",
    rating: 5,
    body: "Усуканата плетка изглежда много интересно. По-тънка от Milano Forte но пък стои много елегантно.",
    imageUrl: "/reviews/bracelet-milano-twist-ВикторП.webp",
    date: "2026-05-20",
  },
  {
    id: "r-46",
    productSlug: "bracelet-milano-twist",
    author: "Георги В.",
    rating: 5,
    body: "Взех я заедно с колие и получих отстъпката за комплект. Много добра комбинация, стоят перфектно заедно.",
    imageUrl: "/reviews/bracelet-milano-twist-ГеоргиВ.webp",
    date: "2026-03-08",
  },
  {
    id: "r-47",
    productSlug: "bracelet-milano-twist",
    author: "Димитър В.",
    rating: 5,
    body: "Хубава гривна. Носи се удобно, не се закача. Позлатата е равномерна и издържа добре.",
    imageUrl: "/reviews/bracelet-milano-twist-ДимитърВ.webp",
    date: "2025-11-02",
  },
  {
    id: "r-48",
    productSlug: "bracelet-milano-twist",
    author: "Мартин К.",
    rating: 5,
    body: "Много доволен от покупката. Гривната изглежда скъпа, а цената е много достъпна.",
    imageUrl: "/reviews/bracelet-milano-twist-МартинК.webp",
    date: "2025-08-14",
  },
  {
    id: "r-49",
    productSlug: "bracelet-milano-twist",
    author: "Пламен С.",
    rating: 5,
    body: "Стои страхотно на китката. Купих я заедно с часовник и изглеждат перфектно заедно.",
    date: "2025-05-22",
  },

  // ─── BRACELET MILANO TWIST — допълнителни текстови ──────────────────────────
  {
    id: "r-320",
    productSlug: "bracelet-milano-twist",
    author: "Иван П.",
    rating: 5,
    body: "Честно казано не очаквах да ми хареса толкова, но на живо е супер.",
    date: "2026-05-09",
  },
  {
    id: "r-321",
    productSlug: "bracelet-milano-twist",
    author: "Николай С.",
    rating: 5,
    body: "Стои фиксирано, не се върти. Имал съм гривни, дето постоянно мигрираха.",
    date: "2026-05-03",
  },
  {
    id: "r-322",
    productSlug: "bracelet-milano-twist",
    author: "Стефан К.",
    rating: 5,
    body: "Забравих, че я имам, но теглото се усеща. Правилен баланс.",
    date: "2026-04-11",
  },
  {
    id: "r-323",
    productSlug: "bracelet-milano-twist",
    author: "Петър М.",
    rating: 5,
    date: "2026-04-19",
  },
  {
    id: "r-324",
    productSlug: "bracelet-milano-twist",
    author: "Кристиан Д.",
    rating: 5,
    body: "Не е прекалено лъскава. Матирането я прави по-сериозна.",
    date: "2026-04-04",
  },
  {
    id: "r-325",
    productSlug: "bracelet-milano-twist",
    author: "Теодор К.",
    rating: 5,
    body: "Стои по-добре отколкото очаквах от снимките.",
    date: "2026-03-24",
  },
  {
    id: "r-326",
    productSlug: "bracelet-milano-twist",
    author: "Радослав М.",
    rating: 5,
    body: "Закопчалката се затваря сигурно. Не треперя да не се разкопчае.",
    date: "2026-03-30",
  },
  {
    id: "r-327",
    productSlug: "bracelet-milano-twist",
    author: "Борис С.",
    rating: 4,
    body: "Тежи приятно и плетката е завършена от всяка страна.",
    date: "2026-03-17",
  },
  {
    id: "r-328",
    productSlug: "bracelet-milano-twist",
    author: "Атанас П.",
    rating: 5,
    body: "Нося я и на работа, и неформално. Стои добре и на риза, и на тениска.",
    date: "2026-03-14",
  },
  {
    id: "r-329",
    productSlug: "bracelet-milano-twist",
    author: "Алекс П.",
    rating: 5,
    date: "2026-03-05",
  },
  {
    id: "r-330",
    productSlug: "bracelet-milano-twist",
    author: "Стоян К.",
    rating: 4,
    body: "Получих я бързо, но кутията беше смачкана",
    date: "2026-02-27",
  },
  {
    id: "r-331",
    productSlug: "bracelet-milano-twist",
    author: "Емил П.",
    rating: 5,
    body: "Твистовата плетка е по-интересна от кубана. Стои добре до часовник.",
    date: "2026-02-05",
  },
  {
    id: "r-332",
    productSlug: "bracelet-milano-twist",
    author: "Калоян М.",
    rating: 5,
    body: "Взех за себе си и за приятел. Двамата я носим.",
    date: "2026-01-29",
  },
  {
    id: "r-333",
    productSlug: "bracelet-milano-twist",
    author: "Мирослав Д.",
    rating: 5,
    date: "2026-01-24",
  },
  {
    id: "r-334",
    productSlug: "bracelet-milano-twist",
    author: "Любомир В.",
    rating: 5,
    date: "2026-01-18",
  },
  {
    id: "r-335",
    productSlug: "bracelet-milano-twist",
    author: "Тодор С.",
    rating: 5,
    body: "По-фина е, но се усеща стабилна.",
    date: "2026-01-11",
  },
  {
    id: "r-336",
    productSlug: "bracelet-milano-twist",
    author: "Борян П.",
    rating: 5,
    date: "2026-01-08",
  },
  {
    id: "r-337",
    productSlug: "bracelet-milano-twist",
    author: "Александър Ц.",
    rating: 5,
    body: "Нито прекалено официална, нито евтино изглеждаща. Намери средата.",
    date: "2025-12-30",
  },
  {
    id: "r-338",
    productSlug: "bracelet-milano-twist",
    author: "Радослав П.",
    rating: 5,
    body: "Три седмици и цветът е непроменен.",
    date: "2025-12-02",
  },
  {
    id: "r-339",
    productSlug: "bracelet-milano-twist",
    author: "Венцислав Д.",
    rating: 5,
    body: "По-фина от кубана, но все пак се забелязва.",
    date: "2025-12-15",
  },
  {
    id: "r-340",
    productSlug: "bracelet-milano-twist",
    author: "Николай Г.",
    rating: 5,
    date: "2025-12-10",
  },
  {
    id: "r-341",
    productSlug: "bracelet-milano-twist",
    author: "Пламен Г.",
    rating: 5,
    body: "Нося я с часовник и колие. Не претрупва визията.",
    date: "2025-11-25",
  },
  {
    id: "r-342",
    productSlug: "bracelet-milano-twist",
    author: "Владимир К.",
    rating: 5,
    body: "Изглежда деликатна, но закопчалката е много здрава. Имал съм вериги, дето са се разкопчавали сами.",
    date: "2025-12-24",
  },

  // ─── BRACELET SIGNATURE ─────────────────────────────────────────────────────
  {
    id: "r-51",
    productSlug: "bracelet-signature",
    author: "Венцислав Г.",
    rating: 5,
    body: "Много доволен. Гривната е точно каквото исках, изчистена, без да е прекалено натрапчива.",
    imageUrl: "/reviews/bracelet-signature-ВенциславГ.webp",
    date: "2026-02-28",
  },
  {
    id: "r-52",
    productSlug: "bracelet-signature",
    author: "Искрен К.",
    rating: 4,
    body: "Стои много елегантно и дискретно. Закопчалката е много стабилна.",
    imageUrl: "/reviews/bracelet-signature-ИскренК.webp",
    date: "2025-12-18",
  },
  {
    id: "r-53",
    productSlug: "bracelet-signature",
    author: "Момчил В.",
    rating: 5,
    body: "Страхотна покупка! 6мм е точната ширина, не е нито много тънка нито много дебела. Препоръчвам.",
    imageUrl: "/reviews/bracelet-signature-МомчилВ.webp",
    date: "2025-09-04",
  },
  {
    id: "r-54",
    productSlug: "bracelet-signature",
    author: "Павлин М.",
    rating: 5,
    body: "Гривната е перфектна за всекидневно носене. Не дразни кожата, хипоалергенна е. Много доволен.",
    imageUrl: "/reviews/bracelet-signature-ПавлинМ.webp",
    date: "2025-06-10",
  },

  // ─── BRACELET SIGNATURE — допълнителни текстови ─────────────────────────────
  {
    id: "r-310",
    productSlug: "bracelet-signature",
    author: "Найден С.",
    rating: 5,
    body: "Кръстчето и кръгчето правят дизайна по-специален.",
    date: "2025-12-22",
  },
  {
    id: "r-311",
    productSlug: "bracelet-signature",
    author: "Леонид К.",
    rating: 5,
    body: "Взех я без много очаквания, но реално ми стана една от любимите.",
    date: "2025-12-13",
  },
  {
    id: "r-312",
    productSlug: "bracelet-signature",
    author: "Спас П.",
    rating: 5,
    body: "Стои естествено на китката и не изглежда претрупана.",
    date: "2025-12-08",
  },
  {
    id: "r-313",
    productSlug: "bracelet-signature",
    author: "Костадин М.",
    rating: 5,
    body: "Дизайнът е дискретен, но прави впечатление.",
    date: "2025-11-02",
  },
  {
    id: "r-314",
    productSlug: "bracelet-signature",
    author: "Георгиан П.",
    rating: 5,
    body: "Месец насам, включително два пъти на басейн. Покритието е непроменено.",
    date: "2025-10-18",
  },
  {
    id: "r-315",
    productSlug: "bracelet-signature",
    author: "Ясен Н.",
    rating: 5,
    body: "Звената са гладки дори отблизо. Изненадах се от нивото на завършеност.",
    date: "2025-10-09",
  },

  // ─── NECKLACE AURELIUS CROSS ─────────────────────────────────────────────────
  {
    id: "r-55",
    productSlug: "necklace-aurelius",
    author: "Любен С.",
    rating: 5,
    body: "Колието е страхотно. Кръстът е с перфектни размери, достатъчно голям да се вижда, без да е прекалено.",
    imageUrl: "/reviews/necklace-aurelius-ЛюбенС.webp",
    date: "2026-05-08",
  },
  {
    id: "r-56",
    productSlug: "necklace-aurelius",
    author: "Митко Т.",
    rating: 5,
    body: "Много хубав кръст. Позлатата е качествена и равномерна. Нося го всеки ден и изглежда като нов.",
    imageUrl: "/reviews/necklace-aurelius-МиткоТ.webp",
    date: "2026-03-27",
  },
  {
    id: "r-57",
    productSlug: "necklace-aurelius",
    author: "Радомир К.",
    rating: 5,
    body: "Верижката е качествена, а самият кръст е много прецизно изработен.",
    imageUrl: "/reviews/necklace-aurelius-РадомирК.webp",
    date: "2026-01-15",
  },
  {
    id: "r-58",
    productSlug: "necklace-aurelius",
    author: "Сашо Т.",
    rating: 5,
    body: "Взех го заедно с гривна Diamante Cross и стоят перфектно заедно. Отстъпката за комплект е страхотна.",
    imageUrl: "/reviews/necklace-aurelius-СашоТ.webp",
    date: "2025-10-19",
  },
  {
    id: "r-59",
    productSlug: "necklace-aurelius",
    author: "Яни М.",
    rating: 5,
    body: "Много съм доволен от колието. Носих го на море и в басейн, нищо не му е станало. Качеството е налице.",
    imageUrl: "/reviews/necklace-aurelius-ЯниМ.webp",
    date: "2025-07-30",
  },
  {
    id: "r-400",
    productSlug: "necklace-aurelius",
    author: "Денис П.",
    rating: 5,
    body: "Веригата и кръстът са в перфектен баланс. Нито прекалено масивно, нито невидимо.",
    date: "2026-04-18",
  },
  {
    id: "r-401",
    productSlug: "necklace-aurelius",
    author: "Валери С.",
    rating: 5,
    body: "Три седмици ежедневно, без забележки. Детайлите са изненадващи отблизо.",
    date: "2026-04-09",
  },
  {
    id: "r-402",
    productSlug: "necklace-aurelius",
    author: "Божидар М.",
    rating: 5,
    body: "Още като го сложих ми направи впечатление, че стои много добре и не изглежда евтино. Кръстът е изчистен, но си личи по детайлите, че е направен както трябва.",
    date: "2026-04-04",
  },
  {
    id: "r-403",
    productSlug: "necklace-aurelius",
    author: "Слави Д.",
    rating: 5,
    body: "Честно казано на живо ми хареса повече, отколкото на снимките.",
    date: "2026-03-27",
  },
  {
    id: "r-404",
    productSlug: "necklace-aurelius",
    author: "Венелин К.",
    rating: 5,
    body: "Хареса ми, че не е никакъв лъскав и кичозен кръст, а по-скоро класически и мъжки.",
    date: "2026-03-20",
  },
  {
    id: "r-405",
    productSlug: "necklace-aurelius",
    author: "Александър Г.",
    rating: 5,
    body: "Взех го без да имам някакви огромни очаквания, но останах супер доволен. Стои много добре на врата.",
    date: "2026-03-15",
  },
  {
    id: "r-406",
    productSlug: "necklace-aurelius",
    author: "Григор П.",
    rating: 4,
    body: "Нося го вече няколко дни и засега всичко е точно. Понякога се усуква, но само като тренирам с него.",
    date: "2026-03-09",
  },
  {
    id: "r-407",
    productSlug: "necklace-aurelius",
    author: "Иво М.",
    rating: 5,
    body: "Ръбовете са гладки и покритието е равномерно. Планирам и верижка Milano.",
    date: "2026-03-02",
  },
  {
    id: "r-408",
    productSlug: "necklace-aurelius",
    author: "Марио К.",
    rating: 4,
    body: "Веригата също ми допадна, защото не изглежда тънка и евтина. Пасва си много добре с кръста.",
    date: "2026-02-18",
  },
  {
    id: "r-409",
    productSlug: "necklace-aurelius",
    author: "Наско П.",
    rating: 4,
    body: "Исках нещо семпло, но да има присъствие, и това точно такова се оказа.",
    date: "2026-02-12",
  },
  {
    id: "r-410",
    productSlug: "necklace-aurelius",
    author: "Росен Д.",
    rating: 4,
    body: "Получих комплимент още първия път, когато го носих навън, така че явно прави впечатление.",
    date: "2026-02-03",
  },
  {
    id: "r-411",
    productSlug: "necklace-aurelius",
    author: "Пенко М.",
    rating: 5,
    date: "2026-01-29",
  },
  {
    id: "r-412",
    productSlug: "necklace-aurelius",
    author: "Тони К.",
    rating: 5,
    body: "Харесва ми, че златистият цвят не бие на евтино жълто. Изглежда доста добре на живо.",
    date: "2026-01-21",
  },
  {
    id: "r-413",
    productSlug: "necklace-aurelius",
    author: "Цецо П.",
    rating: 5,
    body: "Като качество доста ме изненада приятно. Очаквах да е окей, а то реално изглежда много по-добре.",
    date: "2026-01-14",
  },
  {
    id: "r-414",
    productSlug: "necklace-aurelius",
    author: "Симеон В.",
    rating: 5,
    date: "2026-01-09",
  },
  {
    id: "r-415",
    productSlug: "necklace-aurelius",
    author: "Добромир Т.",
    rating: 5,
    body: "На врата стои супер. Нито е натрапчив, нито остава незабелязан.",
    date: "2026-01-03",
  },
  {
    id: "r-416",
    productSlug: "necklace-aurelius",
    author: "Красен В.",
    rating: 5,
    body: "Личи си, че дизайнът е мислен. Има присъствие, но не е прекален.",
    date: "2025-12-27",
  },
  {
    id: "r-417",
    productSlug: "necklace-aurelius",
    author: "Владимир П.",
    rating: 5,
    body: "Стои мъжки и стилно. Не е нито прекалено модерен, нито старомоден.",
    date: "2025-12-25",
  },
  {
    id: "r-418",
    productSlug: "necklace-aurelius",
    author: "Никола П.",
    rating: 5,
    body: "Взех го за ежедневно носене. Не е от аксесоарите, които стоят хубаво само на снимка.",
    date: "2025-12-24",
  },
  {
    id: "r-419",
    productSlug: "necklace-aurelius",
    author: "Спас Д.",
    rating: 5,
    body: "На живо кръстът изглежда доста по-релефен и интересен.",
    date: "2025-12-09",
  },
  {
    id: "r-420",
    productSlug: "necklace-aurelius",
    author: "Ценко В.",
    rating: 5,
    body: "Бях леко скептичен преди да го поръчам, но като дойде, останах приятно изненадан.",
    date: "2025-11-30",
  },
  {
    id: "r-421",
    productSlug: "necklace-aurelius",
    author: "Тихомир Д.",
    rating: 5,
    body: "Кръстът е точно с правилния размер. Ако беше по-голям, щеше да е прекалено, ако беше по-малък, нямаше да изпъква така.",
    date: "2025-11-17",
  },
  {
    id: "r-422",
    productSlug: "necklace-aurelius",
    author: "Пламен В.",
    rating: 5,
    body: "Много добро попадение. От доста време търсех такъв модел, който да е изчистен, но да не изглежда скучно.",
    date: "2025-11-10",
  },
  {
    id: "r-423",
    productSlug: "necklace-aurelius",
    author: "Мартин Г.",
    rating: 5,
    body: "Веригата и медальонът си пасват много добре, което не винаги е така при такива колиета.",
    date: "2025-11-05",
  },
  {
    id: "r-424",
    productSlug: "necklace-aurelius",
    author: "Горан Д.",
    rating: 5,
    body: "Първото, което ми направи впечатление, е колко детайлен е релефът на кръста.",
    date: "2025-10-30",
  },
  {
    id: "r-425",
    productSlug: "necklace-aurelius",
    author: "Живко Н.",
    rating: 5,
    date: "2025-10-23",
  },
  {
    id: "r-426",
    productSlug: "necklace-aurelius",
    author: "Борил К.",
    rating: 5,
    body: "Хваща светлина по интересен начин. Исках дискретно с характер и го намерих.",
    date: "2025-10-20",
  },
  {
    id: "r-427",
    productSlug: "necklace-aurelius",
    author: "Анто П.",
    rating: 4,
    body: "Месец ежедневно, никакви проблеми. Стои добре и на официален повод.",
    date: "2025-10-11",
  },

  // ─── NECKLACE GRANDE IMPERIALE ───────────────────────────────────────────────
  {
    id: "r-60",
    productSlug: "necklace-grande-imperiale",
    author: "Александър Д.",
    rating: 5,
    body: "Масивен и внушителен кръст. Точно каквото търсих. Позлатата е дебела и равномерна. Много доволен.",
    imageUrl: "/reviews/necklace-grande-imperiale-АлександърД.webp",
    date: "2026-05-25",
  },
  {
    id: "r-61",
    productSlug: "necklace-grande-imperiale",
    author: "Борис К.",
    rating: 5,
    body: "Колието е страхотно! Кръстът е с перфектни размери, голям но не прекалено тежък. Стои добре.",
    imageUrl: "/reviews/necklace-grande-imperiale-БорисК.webp",
    date: "2026-04-10",
  },
  {
    id: "r-64",
    productSlug: "necklace-grande-imperiale",
    author: "Мартин П.",
    rating: 5,
    body: "Впечатляващо колие. Заглеждат ме навсякъде. За тези пари е абсолютно страхотно.",
    imageUrl: "/reviews/necklace-grande-imperiale-МартинП.webp",
    date: "2025-09-16",
  },
  {
    id: "r-430",
    productSlug: "necklace-grande-imperiale",
    author: "Иван К.",
    rating: 5,
    body: "Размерът му е по-голям и точно това ми хареса. Не остава незабелязан.",
    date: "2026-05-01",
  },
  {
    id: "r-431",
    productSlug: "necklace-grande-imperiale",
    author: "Георги М.",
    rating: 5,
    body: "Изработката е много чиста, без груби ръбове.",
    date: "2026-04-22",
  },
  {
    id: "r-432",
    productSlug: "necklace-grande-imperiale",
    author: "Петър Д.",
    rating: 5,
    body: "Стои стабилно и не се обръща постоянно.",
    date: "2026-04-17",
  },
  {
    id: "r-433",
    productSlug: "necklace-grande-imperiale",
    author: "Николай К.",
    rating: 5,
    body: "Носил съм подобни, дето след седмица позеленяват. Тук нямам такъв проблем.",
    date: "2026-04-09",
  },
  {
    id: "r-434",
    productSlug: "necklace-grande-imperiale",
    author: "Стефан П.",
    rating: 5,
    body: "Кръстът има тежест и това създава усещане за стойност. Относно цвета, докарва го като истинско злато.",
    date: "2026-04-02",
  },
  {
    id: "r-435",
    productSlug: "necklace-grande-imperiale",
    author: "Кристиан С.",
    rating: 5,
    body: "Подариха ми го. Когато го извадих от кутията, дори аз останах впечатлен.",
    date: "2026-03-28",
  },
  {
    id: "r-436",
    productSlug: "necklace-grande-imperiale",
    author: "Радослав Д.",
    rating: 5,
    body: "Носих го върху тениска и стои много силно като акцент.",
    date: "2026-03-22",
  },
  {
    id: "r-437",
    productSlug: "necklace-grande-imperiale",
    author: "Атанас М.",
    rating: 5,
    date: "2026-03-12",
  },
  {
    id: "r-438",
    productSlug: "necklace-grande-imperiale",
    author: "Димитър С.",
    rating: 5,
    date: "2026-03-03",
  },
  {
    id: "r-439",
    productSlug: "necklace-grande-imperiale",
    author: "Йордан К.",
    rating: 5,
    date: "2026-02-16",
  },
  {
    id: "r-440",
    productSlug: "necklace-grande-imperiale",
    author: "Васил М.",
    rating: 5,
    date: "2026-02-11",
  },
  {
    id: "r-441",
    productSlug: "necklace-grande-imperiale",
    author: "Емил С.",
    rating: 4,
    body: "Стои масивно на врата и не изглежда кухо. Разликата с по-скъпите не е толкова голяма.",
    date: "2026-02-03",
  },
  {
    id: "r-442",
    productSlug: "necklace-grande-imperiale",
    author: "Калоян Д.",
    rating: 5,
    body: "Бих го препоръчал на човек, който иска по-силен и мъжки стил.",
    date: "2026-01-27",
  },

  // ─── NECKLACE MILANO FORTE ───────────────────────────────────────────────────
  {
    id: "r-65",
    productSlug: "necklace-milano-forte",
    author: "Иван М.",
    rating: 5,
    body: "Масивна верижка с много хубав вид. Тежи приятно и изглежда скъпо. Много доволен от покупката.",
    imageUrl: "/reviews/necklace-milano-forte-ИванМ.webp",
    date: "2026-05-01",
  },
  {
    id: "r-66",
    productSlug: "necklace-milano-forte",
    author: "Стефан Д.",
    rating: 5,
    body: "Взех го заедно с гривна Milano Forte и стоят перфектно заедно. Отстъпката при комплект е страхотна идея.",
    imageUrl: "/reviews/necklace-milano-forte-СтефанД.webp",
    date: "2026-03-24",
  },
  {
    id: "r-67",
    productSlug: "necklace-milano-forte",
    author: "Лъчезар Т.",
    rating: 5,
    body: "Плетката е равномерна и добре завършена. Стои добре под ризата.",
    date: "2025-11-17",
  },
  {
    id: "r-450",
    productSlug: "necklace-milano-forte",
    author: "Мартин С.",
    rating: 5,
    body: "Стои много добре на врата и има точно този плътен вид, който търсех.",
    date: "2026-05-21",
  },
  {
    id: "r-451",
    productSlug: "necklace-milano-forte",
    author: "Даниел К.",
    rating: 5,
    body: "Още като го извадих ми направи впечатление, че не изглежда лек и евтин.",
    date: "2026-05-18",
  },
  {
    id: "r-452",
    productSlug: "necklace-milano-forte",
    author: "Петър В.",
    rating: 5,
    body: "Цветът е уцелен доста добре. Не бие на прекалено жълто и стои естествено.",
    date: "2026-05-09",
  },
  {
    id: "r-453",
    productSlug: "necklace-milano-forte",
    author: "Калоян П.",
    rating: 5,
    body: "Закопчалката хваща здраво и досега не съм имал никакви забележки. Преди имах такъв от друга марка, дето постоянно се разкопчаваше.",
    date: "2026-05-03",
  },
  {
    id: "r-454",
    productSlug: "necklace-milano-forte",
    author: "Георги Н.",
    rating: 4,
    body: "Малко по-масивен е, но точно това всъщност ми хареса като го сложих.",
    date: "2026-04-24",
  },
  {
    id: "r-455",
    productSlug: "necklace-milano-forte",
    author: "Атанас М.",
    rating: 5,
    date: "2026-04-11",
  },
  {
    id: "r-456",
    productSlug: "necklace-milano-forte",
    author: "Кристиан П.",
    rating: 4,
    body: "По-къс е отколкото си мислех.",
    date: "2026-04-04",
  },
  {
    id: "r-457",
    productSlug: "necklace-milano-forte",
    author: "Николай Д.",
    rating: 5,
    body: "Хареса ми, че звената изглеждат плътни и добре направени.",
    date: "2026-03-30",
  },
  {
    id: "r-458",
    productSlug: "necklace-milano-forte",
    author: "Борис В.",
    rating: 5,
    body: "Очаквах да е по-обикновен, а то на живо си има присъствие.",
    date: "2026-03-24",
  },
  {
    id: "r-459",
    productSlug: "necklace-milano-forte",
    author: "Емил П.",
    rating: 5,
    body: "Блясъкът е точен, не е прекалено лъскав и не изглежда кичозно.",
    date: "2026-03-14",
  },
  {
    id: "r-460",
    productSlug: "necklace-milano-forte",
    author: "Йордан М.",
    rating: 5,
    body: "Нося го понякога под риза, понякога върху тениска. Изпъква и в двата случая.",
    date: "2026-02-13",
  },
  {
    id: "r-461",
    productSlug: "necklace-milano-forte",
    author: "Васил П.",
    rating: 5,
    body: "Плетката изглежда много добре отблизо. Личи си по детайла.",
    date: "2026-02-05",
  },
  {
    id: "r-462",
    productSlug: "necklace-milano-forte",
    author: "Пламен В.",
    rating: 5,
    body: "Има хубав мъжки вид и не стои като евтин аксесоар.",
    date: "2026-01-18",
  },
  {
    id: "r-463",
    productSlug: "necklace-milano-forte",
    author: "Мирослав К.",
    rating: 5,
    body: "Поръчах го с малко съмнение, но реално останах доволен още като го сложих.",
    date: "2026-01-08",
  },
  {
    id: "r-464",
    productSlug: "necklace-milano-forte",
    author: "Александър Д.",
    rating: 4,
    body: "На тъмни дрехи изпъква супер и стои доста стилно.",
    date: "2026-01-04",
  },
  {
    id: "r-465",
    productSlug: "necklace-milano-forte",
    author: "Антон М.",
    rating: 5,
    body: "Стои балансирано, нито твърде тънък, нито прекалено грамаден.",
    date: "2025-12-30",
  },
  {
    id: "r-466",
    productSlug: "necklace-milano-forte",
    author: "Николай Г.",
    rating: 5,
    body: "Хареса ми, че не изглежда кух и лек, а доста по-солиден.",
    date: "2025-12-24",
  },
  {
    id: "r-467",
    productSlug: "necklace-milano-forte",
    author: "Борислав Д.",
    rating: 5,
    body: "Много добър избор за човек, който иска класически Cuban chain.",
    date: "2025-12-10",
  },
  {
    id: "r-468",
    productSlug: "necklace-milano-forte",
    author: "Иван Д.",
    rating: 5,
    date: "2025-12-02",
  },
  {
    id: "r-469",
    productSlug: "necklace-milano-forte",
    author: "Кирил Д.",
    rating: 4,
    body: "Досега не съм имал проблем нито със закопчалката, нито с самата верига.",
    date: "2025-11-20",
  },
  {
    id: "r-470",
    productSlug: "necklace-milano-forte",
    author: "Атанас К.",
    rating: 5,
    body: "На живо изглежда по-стегнато и по-качествено, отколкото на снимките.",
    date: "2025-11-14",
  },
  {
    id: "r-471",
    productSlug: "necklace-milano-forte",
    author: "Тодор К.",
    rating: 5,
    body: "Ако търсиш по-плътен и изчистен златист ланец, този модел е много добро попадение.",
    date: "2025-11-07",
  },
  {
    id: "r-472",
    productSlug: "necklace-milano-forte",
    author: "Христо П.",
    rating: 5,
    body: "Тежи приятно и стои мъжки. Плетката е добре завършена.",
    date: "2025-10-26",
  },

  // ─── NECKLACE MILANO TWIST ───────────────────────────────────────────────────
  {
    id: "r-68",
    productSlug: "necklace-milano-twist",
    author: "Валери Д.",
    rating: 5,
    body: "Усуканата плетка е уникална. Много елегантна верижка, стои добре и сама и с кръст.",
    imageUrl: "/reviews/necklace-milano-twist-ВалериД.webp",
    date: "2026-04-05",
  },
  {
    id: "r-69",
    productSlug: "necklace-milano-twist",
    author: "Галин П.",
    rating: 5,
    body: "Купих я заедно с гривна Milano Twist. Комплектът изглежда страхотно заедно. Много доволен.",
    imageUrl: "/reviews/necklace-milano-twist-ГалинП.webp",
    date: "2026-01-30",
  },
  {
    id: "r-70",
    productSlug: "necklace-milano-twist",
    author: "Радослав М.",
    rating: 5,
    body: "Много хубава верижка. 6мм ширина е точното, вижда се добре без да е прекалено масивна.",
    date: "2025-08-26",
  },
  {
    id: "r-479",
    productSlug: "necklace-milano-twist",
    author: "Венилин К.",
    rating: 4,
    body: "Преди имах позлатен ланец, обаче си промени цвета след като го намокрих. Беше и значително по-евтин. Засега съм доволен от този.\nВлизах в басейн с него и няма промяна. Препоръчвам.\nЕдинствено кутията беше леко смачкана когато го получих от Еконт. Затова оставям оценка 4.\nСкоро ще поръчам и гривната. Ще има ли намаление скоро?",
    imageUrl: "/reviews/necklace-milano-twist-venilin.jpg",
    date: "2026-05-28",
  },
  {
    id: "r-480",
    productSlug: "necklace-milano-twist",
    author: "Ивайло С.",
    rating: 5,
    body: "Търсех нещо по-леко като визия и този ланец ми пасна точно.",
    date: "2026-04-13",
  },
  {
    id: "r-481",
    productSlug: "necklace-milano-twist",
    author: "Пламен К.",
    rating: 5,
    body: "Плетката не е от баналните модели и веднага се отличава.",
    date: "2026-03-29",
  },
  {
    id: "r-482",
    productSlug: "necklace-milano-twist",
    author: "Станислав Д.",
    rating: 5,
    body: "Хареса ми, че има характер, а не е просто поредният златист ланец.",
    date: "2026-03-24",
  },
  {
    id: "r-483",
    productSlug: "necklace-milano-twist",
    author: "Тодор М.",
    rating: 5,
    body: "На дневна светлина се вижда много хубаво самата усукана структура.",
    date: "2026-03-18",
  },
  {
    id: "r-484",
    productSlug: "necklace-milano-twist",
    author: "Красимир К.",
    rating: 5,
    body: "Плетката му прави много хубаво отражение и това се вижда веднага.",
    date: "2026-03-11",
  },
  {
    id: "r-485",
    productSlug: "necklace-milano-twist",
    author: "Румен К.",
    rating: 5,
    body: "По-семпъл е от масивните модели, но точно това му е чарът.",
    date: "2026-03-08",
  },
  {
    id: "r-486",
    productSlug: "necklace-milano-twist",
    author: "Веселин П.",
    rating: 5,
    body: "Нося го всеки ден и изобщо не ми омръзва.",
    date: "2026-02-27",
  },
  {
    id: "r-487",
    productSlug: "necklace-milano-twist",
    author: "Божидар С.",
    rating: 5,
    body: "Избрах го, защото не исках нещо прекалено дебело, и се оказа правилен избор.",
    date: "2026-02-21",
  },
  {
    id: "r-488",
    productSlug: "necklace-milano-twist",
    author: "Людмил П.",
    rating: 5,
    date: "2026-02-07",
  },
  {
    id: "r-489",
    productSlug: "necklace-milano-twist",
    author: "Деян С.",
    rating: 5,
    date: "2026-01-23",
  },
  {
    id: "r-490",
    productSlug: "necklace-milano-twist",
    author: "Костадин М.",
    rating: 5,
    date: "2026-01-18",
  },
  {
    id: "r-491",
    productSlug: "necklace-milano-twist",
    author: "Явор К.",
    rating: 5,
    date: "2026-01-12",
  },
  {
    id: "r-492",
    productSlug: "necklace-milano-twist",
    author: "Симеон П.",
    rating: 5,
    date: "2026-01-05",
  },
  {
    id: "r-493",
    productSlug: "necklace-milano-twist",
    author: "Златко Д.",
    rating: 5,
    date: "2026-01-02",
  },
  {
    id: "r-494",
    productSlug: "necklace-milano-twist",
    author: "Орлин К.",
    rating: 5,
    body: "Има по-интересна форма от стандартните синджири и точно това ме спечели.",
    date: "2025-12-24",
  },
  {
    id: "r-495",
    productSlug: "necklace-milano-twist",
    author: "Росен П.",
    rating: 5,
    body: "На снимка не му личи толкова, но отблизо плетката е много приятна.",
    date: "2025-12-18",
  },
  {
    id: "r-496",
    productSlug: "necklace-milano-twist",
    author: "Милен Д.",
    rating: 5,
    body: "Добър е за човек, който иска златист ланец, но без да е прекалено тежкарски.",
    date: "2025-12-09",
  },
  {
    id: "r-497",
    productSlug: "necklace-milano-twist",
    author: "Живко К.",
    rating: 5,
    date: "2025-11-26",
  },
  {
    id: "r-498",
    productSlug: "necklace-milano-twist",
    author: "Николай Ц.",
    rating: 5,
    body: "Това е от малкото модели, които изглеждат добре и с ежедневни, и с по-стегнати дрехи.",
    date: "2025-11-14",
  },
  {
    id: "r-499",
    productSlug: "necklace-milano-twist",
    author: "Велко П.",
    rating: 5,
    body: "Хареса ми как пада отпред, не стои твърдо.",
    date: "2025-11-08",
  },
  {
    id: "r-500",
    productSlug: "necklace-milano-twist",
    author: "Иван Б.",
    rating: 5,
    date: "2025-11-01",
  },
  {
    id: "r-501",
    productSlug: "necklace-milano-twist",
    author: "Кирил Т.",
    rating: 5,
    body: "Стои добре и сам, без да има нужда от висулка.",
    date: "2025-10-29",
  },
  {
    id: "r-502",
    productSlug: "necklace-milano-twist",
    author: "Александър В.",
    rating: 4,
    body: "Като цяло много сполучлив ланец и съм доволен, че избрах точно него.",
    date: "2025-10-14",
  },
  {
    id: "r-503",
    productSlug: "necklace-milano-twist",
    author: "Борис Д.",
    rating: 5,
    body: "Плетката го прави по-интересен дори без никакъв медальон.",
    date: "2025-10-05",
  },
  {
    id: "r-504",
    productSlug: "necklace-milano-twist",
    author: "Стефан В.",
    rating: 5,
    body: "Цветът не е прекален и това много ми допадна.",
    date: "2025-09-30",
  },
  {
    id: "r-505",
    productSlug: "necklace-milano-twist",
    author: "Денис Г.",
    rating: 4,
    body: "Имам и по-дебел ланец, но този ми е по-удобен за носене.",
    date: "2025-09-22",
  },

  // ─── CHRONO BLACK ──────────────────────────────────────────────────────────
  {
    id: "r-201",
    productSlug: "chrono-black",
    author: "Борислав Н.",
    rating: 5,
    body: "Качествен, точен. Кутията също ме изкефи",
    imageUrl: "/reviews/chrono-black-borislav.jpg",
    date: "2026-05-18",
  },
  {
    id: "r-202",
    productSlug: "chrono-black",
    author: "Станимир Г.",
    rating: 5,
    body: "Бутоните и коронката щракат стабилно, хронографът работи точно. Стъклото не се драска, поне при мен след месец носене е като нов.",
    imageUrl: "/reviews/chrono-black-stanimir.jpg",
    date: "2026-05-09",
  },
  {
    id: "r-204",
    productSlug: "chrono-black",
    author: "Атанас В.",
    rating: 5,
    body: "Масивен и впечатляващ. Точно такъв го исках – да изглежда скъп и да стои добре на китката. Много доволен.",
    imageUrl: "/reviews/chrono-black-atanas.jpg",
    date: "2026-04-28",
  },
  {
    id: "r-205",
    productSlug: "chrono-black",
    author: "Калоян Т.",
    rating: 5,
    body: "Каишката е мека и диша, не запарява и държи здраво. Носих го цял ден, не тежи и не се усеща на китката.",
    date: "2026-04-24",
  },
  {
    id: "r-206",
    productSlug: "chrono-black",
    author: "Йордан Д.",
    rating: 5,
    body: "Ползвам го и на работа, и във фитнеса. Каишката с отворите диша, не се хлъзга, а часовникът не мърда. Абсолютно доволен.",
    imageUrl: "/reviews/chrono-black-yordan-d.jpg",
    date: "2026-04-19",
  },
  {
    id: "r-90",
    productSlug: "chrono-black",
    author: "Иван Н.",
    rating: 5,
    body: "Поръчах го, защото отива на всякакви дрехи. По Еконт дойде с хубава кутия. Супер е",
    imageUrl: "/reviews/chrono-black-ИванНиколов.webp",
    date: "2024-09-08",
  },
  {
    id: "r-91",
    productSlug: "chrono-black",
    author: "Михаел В.",
    rating: 5,
    body: "Стои много добре на китката. Стоманата е масивна и качествена.",
    imageUrl: "/reviews/chrono-black-михаелв.webp",
    date: "2024-09-07",
  },
  {
    id: "r-100",
    productSlug: "chrono-black",
    author: "Виктор К.",
    rating: 5,
    body: "Търсех хронограф с японски механизъм и го намерих. Точен, изчистен.",
    date: "2024-09-08",
  },

  // ─── GOLDEN ECLIPSE ────────────────────────────────────────────────────────
  {
    id: "r-110",

    productSlug: "golden-eclipse",
    author: "Павел Дойчев",
    rating: 5,
    body: "Часовника е уникат!! Забелязва се от далеч и изглежда супер скъп. За тези пари е наистина страхотен",
    imageUrl: "/reviews/golden-eclipse-pavel-doychev.jpg",
    date: "2024-09-10",
  },
  {
    id: "r-117",
    productSlug: "golden-eclipse",
    author: "Милен Т.",
    rating: 5,
    body: "Бях скептичен, на живо се оказа по-хубав. Ще го взема и за подарък.",
    date: "2024-09-09",
  },
  {
    id: "r-119",
    productSlug: "golden-eclipse",
    author: "Николай С.",
    rating: 5,
    body: "Много солиден часовник. Циферблатът има страхотна дълбочина на живо, а механизмът е безупречен.",
    date: "2024-09-08",
  },
  {
    id: "r-122",
    productSlug: "golden-eclipse",
    author: "Борис К.",
    rating: 5,
    body: "Циферблатът изглежда по-наситен на живо. Засега без забележки.",
    date: "2024-09-07",
  },

  // ─── POLAR FROST ───────────────────────────────────────────────────────────
  {
    id: "r-130",
    productSlug: "polar-frost",
    author: "Станислав К.",
    rating: 5,
    body: "Изработката е много стабилна. Стъклото е кристално чисто.",
    imageUrl: "/reviews/polar-frost-СтаниславКовачев.webp",
    date: "2024-09-09",
  },
  {
    id: "r-133",
    productSlug: "polar-frost",
    author: "Светлин Х.",
    rating: 5,
    body: "Уникален часовник, много е красив на живо.",
    date: "2024-06-13",
  },
  {
    id: "r-134",
    productSlug: "polar-frost",
    author: "Даниел С.",
    rating: 5,
    body: "Много свеж модел. Синьото се откроява страхотно на живо.",
    date: "2024-09-09",
  },
  {
    id: "r-135",
    productSlug: "polar-frost",
    author: "Павел К.",
    rating: 5,
    body: "Подариха ми го. Кутията при отварянето направи силно впечатление.",
    date: "2024-09-09",
  },
  {
    id: "r-146",
    productSlug: "polar-frost",
    author: "Станимир Х.",
    rating: 5,
    body: "Синият циферблат се забелязва дори под маншет.",
    date: "2024-09-07",
  },

  // ─── WALLET ALABASTRO ────────────────────────────────────────────────────────
  {
    id: "r-600",
    productSlug: "wallet-alabastro",
    author: "Николай Т.",
    rating: 5,
    body: "Кожата има невероятна текстура. Определено се усеща като аксесоар от съвсем различен клас. Опаковката също е на ниво.",
    date: "2026-04-20",
  },
  {
    id: "r-601",
    productSlug: "wallet-alabastro",
    author: "Тодор Б.",
    rating: 5,
    body: "Не личи в джоба на панталона. Кожата е по-мека от очакваното.",
    date: "2026-03-15",
  },
  {
    id: "r-602",
    productSlug: "wallet-alabastro",
    author: "Радослав Д.",
    rating: 5,
    body: "Много чист дизайн. Белият цвят прави силно впечатление, а изработката е безкомпромисна.",
    date: "2026-01-28",
  },
  {
    id: "r-603",
    productSlug: "wallet-alabastro",
    author: "Кристиан С.",
    rating: 4,
    body: "Първите дни беше малко твърд, но крокодилската кожа омекна и легна перфектно по картите. Презентацията е топ.",
    date: "2025-12-10",
  },
  {
    id: "r-604",
    productSlug: "wallet-alabastro",
    author: "Васил М.",
    rating: 5,
    body: "Изключителен минимализъм. Събира най-важното без излишен обем.",
    date: "2025-11-05",
  },

  // ─── WALLET RUBINO ───────────────────────────────────────────────────────────
  {
    id: "r-610",
    productSlug: "wallet-rubino",
    author: "Христо П.",
    rating: 5,
    body: "Дълбок и наситен цвят. Шевовете са перфектни, личи си вниманието към детайла още с отварянето на кутията.",
    date: "2026-05-02",
  },
  {
    id: "r-611",
    productSlug: "wallet-rubino",
    author: "Асен Г.",
    rating: 4,
    body: "Много дълбок цвят. Малко е стегнат за повече от 4 карти в началото, но качеството на материала е безкомпромисно.",
    date: "2026-02-18",
  },
  {
    id: "r-612",
    productSlug: "wallet-rubino",
    author: "Ангел К.",
    rating: 5,
    body: "Изглежда изключително сериозно и тежко. Кожата старее много красиво.",
    date: "2026-01-09",
  },
  {
    id: "r-613",
    productSlug: "wallet-rubino",
    author: "Ивайло Н.",
    rating: 5,
    body: "Шевовете и обработката на ръбовете са перфектни. Страхотен баланс между лукс и функция.",
    date: "2025-10-22",
  },

  // ─── WALLET SMERALDO ─────────────────────────────────────────────────────────
  {
    id: "r-620",
    productSlug: "wallet-smeraldo",
    author: "Пламен Р.",
    rating: 5,
    body: "Изумруденото зелено на живо е още по-впечатляващо. Много стилен и дискретен.",
    date: "2026-04-28",
  },
  {
    id: "r-621",
    productSlug: "wallet-smeraldo",
    author: "Станислав Х.",
    rating: 5,
    body: "Перфектна ергономичност. Тънък силует, който не разваля линията на костюма. Кожата има прекрасен аромат.",
    date: "2026-03-07",
  },
  {
    id: "r-622",
    productSlug: "wallet-smeraldo",
    author: "Юлиян Ф.",
    rating: 5,
    body: "Текстурата на крокодила е напълно уникална. Личи си, че няма втори напълно еднакъв модел.",
    date: "2026-01-19",
  },
  {
    id: "r-623",
    productSlug: "wallet-smeraldo",
    author: "Константин Ц.",
    rating: 5,
    body: "Безупречна изработка. Профилът е тънък и не издува излишно вътрешния джоб на сакото.",
    date: "2025-12-30",
  },
  {
    id: "r-624",
    productSlug: "wallet-smeraldo",
    author: "Стоян В.",
    rating: 5,
    body: "Много стилен аксесоар за хора, които търсят дискретен, но категоричен лукс.",
    date: "2025-11-14",
  },

  // ─── CARDHOLDER AMBRA ────────────────────────────────────────────────────────
  {
    id: "r-630",
    productSlug: "cardholder-ambra",
    author: "Дарин Е.",
    rating: 5,
    body: "Класически топъл цвят. Патината, която започва да хваща с времето, го прави още по-уникален.",
    date: "2026-05-12",
  },
  {
    id: "r-631",
    productSlug: "cardholder-ambra",
    author: "Деян Л.",
    rating: 5,
    body: "Четири карти и банкнота без проблем. Компактен и стабилен.",
    date: "2026-04-24",
  },
  {
    id: "r-632",
    productSlug: "cardholder-ambra",
    author: "Кирил И.",
    rating: 4,
    body: "Картите влизат доста плътно в началото, но естествената кожа пасна точно колкото трябва след ден-два.",
    date: "2026-03-30",
  },
  {
    id: "r-633",
    productSlug: "cardholder-ambra",
    author: "Мирослав Ж.",
    rating: 5,
    body: "Много компактен и удобен. Точно това, което търсех за ежедневието.",
    date: "2026-02-17",
  },
  {
    id: "r-634",
    productSlug: "cardholder-ambra",
    author: "Цветан Ш.",
    rating: 5,
    body: "Дизайнът е чист, без излишен обем. Приляга идеално във всеки преден джоб.",
    date: "2026-01-28",
  },
  {
    id: "r-635",
    productSlug: "cardholder-ambra",
    author: "Явор А.",
    rating: 5,
    body: "Подариха ми го и останах много приятно изненадан от нивото на изпълнение и презентацията.",
    date: "2025-12-20",
  },
  {
    id: "r-636",
    productSlug: "cardholder-ambra",
    author: "Камен О.",
    rating: 5,
    body: "Уникален органичен релеф. Всеки сантиметър от кожата има собствен характер.",
    date: "2025-11-08",
  },
  {
    id: "r-637",
    productSlug: "cardholder-ambra",
    author: "Теодор У.",
    rating: 4,
    body: "Влиза точно в предния джоб. Не усещам, че го нося.",
    date: "2025-10-15",
  },
  {
    id: "r-638",
    productSlug: "cardholder-ambra",
    author: "Марин Я.",
    rating: 5,
    body: "Месец насам, ръбовете са непроменени. Структурата е здрава.",
    date: "2025-09-24",
  },

  // ─── CARDHOLDER BIANCO ───────────────────────────────────────────────────────
  {
    id: "r-640",
    productSlug: "cardholder-bianco",
    author: "Любомир Т.",
    rating: 5,
    body: "Минимализъм от най-високо ниво. Кожата има много специфично и приятно усещане на допир.",
    date: "2026-05-05",
  },
  {
    id: "r-641",
    productSlug: "cardholder-bianco",
    author: "Росен П.",
    rating: 5,
    body: "Солидна изработка. Изчистени линии и нулев излишен обем за летните джобове.",
    date: "2026-03-11",
  },
  {
    id: "r-642",
    productSlug: "cardholder-bianco",
    author: "Валентин М.",
    rating: 5,
    body: "Текстурата е уникална. Събира най-важното, без да натежава в джоба.",
    date: "2026-01-22",
  },
  {
    id: "r-643",
    productSlug: "cardholder-bianco",
    author: "Филип С.",
    rating: 5,
    body: "Излезе ми на реклама във фейсбук и го поръчах без да ми трябва. Имах си портфейл, но в крайна сметка го замени. Нямам оплаквания, надявам се да издържи дълго време.",
    date: "2025-12-07",
  },

  // ─── CARDHOLDER VALENTINA ────────────────────────────────────────────────────
  {
    id: "r-650",
    productSlug: "cardholder-valentina",
    author: "Живко Д.",
    rating: 5,
    body: "Взех го за подарък на съпругата ми. Цветът е много смел, а качеството надмина очакванията ѝ.",
    date: "2026-04-18",
  },
  {
    id: "r-651",
    productSlug: "cardholder-valentina",
    author: "Богомил И.",
    rating: 4,
    body: "Качеството на екзотичната кожа е безспорно. Малко е стегнат за дебели карти първоначално, но бързо сляга.",
    date: "2026-02-28",
  },
  {
    id: "r-652",
    productSlug: "cardholder-valentina",
    author: "Чавдар К.",
    rating: 5,
    body: "Уникален аксесоар. Дискретен лукс, който се забелязва веднага, без да е натрапчив.",
    date: "2026-01-14",
  },
  {
    id: "r-653",
    productSlug: "cardholder-valentina",
    author: "Страхил Б.",
    rating: 4,
    body: "Фина обработка. Пази се лесно и с времето придобива характер.",
    date: "2025-11-30",
  },

  // ─── CARDHOLDER ZAFFIRO ──────────────────────────────────────────────────────
  {
    id: "r-660",
    productSlug: "cardholder-zaffiro",
    author: "Емилиян Н.",
    rating: 5,
    body: "Дълбок и много улегнал син цвят. Перфектен за хора, които не обичат обемни портфейли.",
    date: "2026-05-08",
  },
  {
    id: "r-661",
    productSlug: "cardholder-zaffiro",
    author: "Здравко Г.",
    rating: 5,
    body: "Картите стоят изключително стабилно. Тънък профил, идеален за носене без чанта.",
    date: "2026-03-19",
  },
  {
    id: "r-662",
    productSlug: "cardholder-zaffiro",
    author: "Момчил С.",
    rating: 5,
    body: "Естественият релеф на кожата прави всеки кардхолдър уникален. Много стабилна изработка.",
    date: "2026-02-02",
  },
  {
    id: "r-663",
    productSlug: "cardholder-zaffiro",
    author: "Дамян В.",
    rating: 5,
    body: "Перфектна геометрия и здрави шевове. Старее изключително красиво при ежедневно носене.",
    date: "2025-12-25",
  },
  {
    id: "r-664",
    productSlug: "cardholder-zaffiro",
    author: "Калин П.",
    rating: 5,
    body: "Тежката опаковка прави впечатление. Кожата е с природен релеф.",
    date: "2025-10-30",
  },
];

export function getReviewsBySlug(slug: string): Review[] {
  return reviews.filter((r) => r.productSlug === slug);
}

export const reviewSummary: Record<string, { count: number; avg: number }> = {
  "bracelet-diamante-cross":   { count: 71,  avg: 4.9 },
  "bracelet-milano-forte":     { count: 49,  avg: 4.7 },
  "bracelet-milano-twist":     { count: 54,  avg: 4.8 },
  "bracelet-signature":        { count: 37,  avg: 4.8 },
  "chrono-black":              { count: 435, avg: 4.77 },
  "golden-eclipse":            { count: 263, avg: 4.87 },
  "necklace-aurelius":         { count: 56,  avg: 4.9 },
  "necklace-grande-imperiale": { count: 27,  avg: 4.8 },
  "necklace-milano-forte":     { count: 47,  avg: 4.7 },
  "necklace-milano-twist":     { count: 59,  avg: 4.8 },
  "polar-frost":               { count: 161, avg: 4.78 },
  "wallet-alabastro":          { count: 24,  avg: 4.8 },
  "wallet-rubino":             { count: 31,  avg: 4.6 },
  "wallet-smeraldo":           { count: 27,  avg: 4.8 },
  "cardholder-ambra":          { count: 34,  avg: 4.8 },
  "cardholder-bianco":         { count: 19,  avg: 4.8 },
  "cardholder-valentina":      { count: 22,  avg: 4.6 },
  "cardholder-zaffiro":        { count: 28,  avg: 4.9 },
};
